"use client"
import Link from "next/link"
import { useParams } from "next/navigation"
import { useEffect,useState } from "react"
import { type MajorResultsPayload } from "@/lib/majors"
import { supabase } from "@/lib/supabase"
type HistoryLeader={player_id:string;player_screen_name_snapshot:string;holes_in_one:number}
export default function MajorStatsPage(){const{slug}=useParams<{slug:string}>();const[data,setData]=useState<MajorResultsPayload|null>(null),[history,setHistory]=useState<HistoryLeader[]>([]);useEffect(()=>{void(async()=>{const e=await supabase.from("major_events").select("id").eq("slug",slug).maybeSingle();if(e.data){const [r,h]=await Promise.all([supabase.rpc("get_public_major_live_results",{p_major_event_id:e.data.id}),supabase.rpc("get_public_major_hole_in_one_history")]);setData(r.data as MajorResultsPayload);setHistory((h.data as HistoryLeader[])||[])}})()},[slug]);if(!data)return<main style={page}>Loading stats…</main>;const map=new Map<string,{name:string,count:number,pending:boolean}>();data.rounds.forEach(r=>r.cards.forEach(c=>{const x=map.get(c.player_id)||{name:c.player_screen_name_snapshot,count:0,pending:false};x.count+=c.holes.filter(h=>h.strokes===1).length;x.pending||=c.status!=="verified";map.set(c.player_id,x)}));const leaders=[...map.values()].sort((a,b)=>b.count-a.count);return<main style={page}><div style={shell}><Link href={`/majors/${slug}/results`}>← Live results</Link>{data.event.is_test_event&&<h2 style={test}>TEST DATA — NOT OFFICIAL</h2>}<h1>Bonus / Live Stats</h1><p style={pending}>SCORES ARE UNOFFICIAL UNTIL VERIFIED.</p><section style={card}><h2>Most Holes in One — Current Major</h2>{leaders.map((x,i)=><p key={x.name}><b>{i+1}. {x.name}</b><strong style={x.pending?pending:official}>{x.count}</strong></p>)}</section><section style={card}><h2>Most Holes in One — Majors History</h2>{history.length?history.map((x,i)=><p key={x.player_id}><b>{i+1}. {x.player_screen_name_snapshot}</b><strong style={official}>{x.holes_in_one}</strong></p>):<p>No verified official Major aces yet.</p>}</section></div></main>}
const page:React.CSSProperties={minHeight:"100vh",padding:20,background:"#07120d",color:"white"},shell:React.CSSProperties={maxWidth:900,margin:"auto"},card:React.CSSProperties={padding:18,border:"1px solid #365347",borderRadius:14,background:"#102219",marginTop:16},pending:React.CSSProperties={color:"#f472b6"},official:React.CSSProperties={color:"#4ade80"},test:React.CSSProperties={background:"#78350f",padding:12}
