"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { PublicRecordsHero, PublicRecordsShell, publicRecordsStyles as styles } from "@/components/records/PublicRecordsUI"
import { canonicalPlayerName, type PublicCombinedRecord } from "@/lib/all-time/public-records"

type RankedCombinedRecord = PublicCombinedRecord & { rank: number | null }

export default function PublicCombinedRecordsPage(){
  const [maps,setMaps]=useState<string[]>([]),[baseMap,setBaseMap]=useState(""),[records,setRecords]=useState<RankedCombinedRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("")
  useEffect(()=>{let cancelled=false;void(async()=>{try{const response=await fetch("/api/records/public?view=combined"),payload=await response.json() as {maps?:string[];error?:string};if(!response.ok)throw new Error(payload.error);if(cancelled)return;const values=payload.maps??[];setMaps(values);setBaseMap(values[0]??"");if(!values.length)setLoading(false)}catch(caught){if(!cancelled){setError(caught instanceof Error?caught.message:"Maps could not be loaded.");setLoading(false)}}})();return()=>{cancelled=true}},[])
  useEffect(()=>{if(!baseMap)return;let cancelled=false;void(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/records/public?view=combined&baseMap=${encodeURIComponent(baseMap)}`),payload=await response.json() as {records?:RankedCombinedRecord[];error?:string};if(!response.ok)throw new Error(payload.error);if(!cancelled)setRecords(payload.records??[])}catch(caught){if(!cancelled){setError(caught instanceof Error?caught.message:"Combined Records could not be loaded.");setRecords([])}}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[baseMap])
  const ranked=records
  return <PublicRecordsShell><nav className={styles.nav}><Link href="/records" className={styles.button}>← Course Records</Link><Link href="/records/single" className={styles.button}>Single Course Records</Link></nav><PublicRecordsHero title="Combined Map Records" description="Combined scores from official KWT and Pro League events. Not open to individual submissions."/><section className={`${styles.glass} ${styles.pad} ${styles.combinedPanel}`}><div className={styles.toolbar}><div><h2 className={styles.heading}>Combined leaderboard</h2><p className={styles.copy}>Rank is calculated from the combined total—not an imported historical rank.</p></div><label className={styles.selectWrap}>Map<select className={styles.select} value={baseMap} onChange={event=>setBaseMap(event.target.value)}>{maps.map(map=><option key={map}>{map}</option>)}</select></label></div>{baseMap&&<><div className={styles.courseMeta}><h3 className={styles.heading}>{baseMap}</h3><span className={styles.badge}>{ranked.length} records</span></div><div className={styles.list}>{ranked.map(record=>{const name=canonicalPlayerName(record);return <div className={styles.row} key={record.id}><div className={styles.rank}>#{record.rank}</div><div><Link className={styles.player} href={`/players/${record.player_id}`}>{name}</Link><div className={styles.components}><span className={styles.combinedEasy}>Easy {record.easy_score}</span><span className={styles.combinedHard}>Hard {record.hard_score}</span></div></div><div className={`${styles.score} ${styles.total}`}>{record.combined_score}</div></div>})}</div></>}{loading&&<div className={styles.empty}>Loading records…</div>}{!loading&&!error&&ranked.length===0&&<div className={styles.empty}>No official combined records are available for this map yet.</div>}{error&&<div role="alert" className={styles.empty}>{error}</div>}</section></PublicRecordsShell>
}
