"use client"
import {useEffect,useRef,useState} from "react";import {useRouter} from "next/navigation";import {supabase} from "@/lib/supabase";
const KEY="pyp-season-create-draft";type Draft={season:string;count:string;start:string;end:string};
export default function PYPSeason(){const router=useRouter();const [season,setSeason]=useState("");const [count,setCount]=useState("5");const [start,setStart]=useState("");const [end,setEnd]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const ready=useRef(false);
// Restore the browser-only draft once when this client page mounts.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{try{const d=JSON.parse(sessionStorage.getItem(KEY)||"{}") as Partial<Draft>;setSeason(d.season||"");setCount(d.count||"5");setStart(d.start||"");setEnd(d.end||"")}catch{sessionStorage.removeItem(KEY)}ready.current=true},[]);useEffect(()=>{if(ready.current)sessionStorage.setItem(KEY,JSON.stringify({season,count,start,end}))},[season,count,start,end]);
async function create(){const n=Number(season),c=Number(count);if(!Number.isInteger(n)||n<1||!Number.isInteger(c)||c<1||c>20||!start||!end||end<start){setMsg("Enter a valid season number, 1–20 divisions, and valid start/end dates.");return}setBusy(true);setMsg("");const {data,error}=await supabase.rpc("create_pyp_season_with_roster",{p_season_number:n,p_division_count:c,p_start_date:start,p_due_date:end,p_end_date:end}).single();setBusy(false);if(error||!data){setMsg(error?.message||"PYP season was not created.");return}sessionStorage.removeItem(KEY);const r=data as {season_id:string;first_division_number:number};router.push(`/admin/pyp/setup?seasonId=${r.season_id}&division=${r.first_division_number}`)}
return <main style={page}><div style={box}><button onClick={()=>router.push("/admin/pyp")}>← PYP Hub</button><h1>Create PYP Season</h1><p>Creates one managed season with four persistent slots per division. Course choices are made per fixture later.</p><div style={grid}><label>Season Number<input type="number" value={season} onChange={e=>setSeason(e.target.value)}/></label><label>Number of Divisions<input type="number" min="1" max="20" value={count} onChange={e=>setCount(e.target.value)}/></label><label>Start Date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End Date<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button disabled={busy} onClick={create}>{busy?"Creating...":"Create PYP Season"}</button>{msg&&<p>{msg}</p>}</div></main>}
const page:React.CSSProperties={minHeight:"100vh",background:"black",color:"white",padding:24};const box:React.CSSProperties={maxWidth:900,margin:"auto",background:"#111",border:"1px solid #333",borderRadius:16,padding:24};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:16,margin:"20px 0"}
