import crypto from "node:crypto"
import fs from "node:fs"
import path from "node:path"
import Link from "next/link"
import { parseKwtSeason9DiscordEvidence, summarizeKwtDiscordSeason } from "@/lib/importer/adapters/kwtDiscordEvidence"
import KwtDiscordIdentityReview from "./KwtDiscordIdentityReview"

export default function Season9DiscordPreviewPage() {
  const sourcePath = path.join(process.cwd(), "docs", "historical-sources", "kwt", "season-09-discord-evidence.txt")
  const bytes = fs.readFileSync(sourcePath)
  const sourceHash = crypto.createHash("sha256").update(bytes).digest("hex")
  const season = parseKwtSeason9DiscordEvidence(bytes.toString("utf8"), sourceHash)
  const summary = summarizeKwtDiscordSeason(season)
  const cards: Array<[string, string | number]> = [["Weeks", summary.weeks], ["Finals", summary.finalsRecognized ? "Recognized" : "Missing"], ["Division placements", summary.divisionPlacementFacts], ["Overall placements", summary.overallPlacementFacts], ["Best Easy recipients", summary.bestEasyFacts], ["Best Hard recipients", summary.bestHardFacts], ["Promotions", summary.promotionFacts], ["Badge multiplicities", summary.badgeMultiplicities], ["Special recognition", summary.specialRecognitions], ["New Player annotations", summary.newPlayerAnnotations]]
  return <main className="min-h-screen bg-zinc-950 px-6 py-10 text-white"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-300">Local V2 · Discord evidence preview</p><h1 className="mt-2 text-4xl font-bold">KWT Season 9 historical results</h1><p className="mt-3 max-w-3xl text-zinc-400">Lossless, read-only preview of authoritative Discord competition facts. Apply, migrations and Production writes are disconnected.</p></div><Link href="/admin/kwt-import" className="rounded-lg border border-zinc-700 px-4 py-2 font-semibold">← KWT library</Link></div>
    <section className="mt-6 rounded-xl border border-amber-800 bg-amber-950/30 p-5"><strong className="text-amber-200">Authority boundary</strong><p className="mt-2 text-amber-100/80">Discord proves historical divisions, placements, ties, promotions, badges and recognition. CSV proves Easy/Hard score observations only. Later CSV Rank Code, Division and Pos are never substituted. Historical imports earn 0 Climbers.</p><p className="mt-2 break-all font-mono text-xs">Source SHA-256: {sourceHash}</p></section>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value]) => <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4" key={label}><p className="text-sm text-zinc-500">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>)}</section>
    <section className="mt-6 rounded-xl border border-zinc-800 bg-zinc-900 p-5"><h2 className="text-xl font-bold">Badge facts</h2><div className="mt-3 flex flex-wrap gap-4">{Object.entries(summary.badgeFacts).map(([type,count]) => <span className="rounded-lg border border-zinc-700 px-3 py-2 capitalize" key={type}>{type}: {count}</span>)}</div></section>
    <div className="mt-6"><KwtDiscordIdentityReview season={season} /></div>
    <section className="mt-6 space-y-4"><h2 className="text-2xl font-bold">Week reconciliation</h2>{season.events.map(event => <article className="rounded-xl border border-zinc-800 bg-zinc-900 p-5" key={event.week}><div className="flex flex-wrap justify-between gap-2"><h3 className="text-xl font-bold">S9 W{event.week} · {event.course}</h3><span>{event.playerCount ?? "Player count not supplied"}</span></div><p className="mt-3 text-sm text-zinc-300">Division placements {event.placements.filter(fact => fact.scope === "division").length} · Overall placements {event.placements.filter(fact => fact.scope === "overall").length} · Awards {event.awards.length} · Promotions {event.promotions.length} · Badges {event.badges.length} · Source sections {event.sourceMessages.length}</p><div className="mt-3 grid gap-3 lg:grid-cols-2"><div><strong>Courses and placement depth</strong><p className="mt-1 text-sm text-zinc-400">Maximum published division position: {Math.max(...event.placements.filter(fact => fact.scope === "division").map(fact => fact.position))}. Tied players retain the same position; skipped ranks are not synthesized.</p></div><div><strong>Unknown versus zero</strong><p className="mt-1 text-sm text-zinc-400">{Object.entries(event.badgeStatus).map(([type,status]) => `${type}: ${status}`).join(" · ")}</p></div></div>{event.annotations.map(value => <p className="mt-2 text-indigo-300" key={value.raw}>@{value.sourceHandle}: {value.text}</p>)}{event.recognitions.map(value => <p className="mt-2 text-green-300" key={value.raw}>@{value.sourceHandle}: {value.text}</p>)}{event.warnings.map(value => <p className="mt-2 text-amber-300" key={value}>{value}</p>)}</article>)}</section>
    <section className="mt-6 rounded-xl border border-zinc-800 bg-zinc-900 p-5"><h2 className="text-xl font-bold">Season 9 finals</h2><p className="mt-2 text-zinc-300">{season.finals.placements.length} final placement facts preserved separately from Week 12. {season.finals.recognitions.map(value => `@${value.sourceHandle}: ${value.text}`).join(" ")}</p><button disabled className="mt-4 cursor-not-allowed rounded-lg bg-zinc-700 px-5 py-3 font-bold text-zinc-400">Apply disabled</button></section>
  </div></main>
}
