import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import {normalizeHistoricalKwtRank,parseHistoricalKwtRows,seasonWeekFromFilename} from "./kwtAdapter.ts"

test("season and week are recovered from historical KWT filenames",()=>{assert.deepEqual(seasonWeekFromFilename("KWT11W03.csv"),{season:11,week:3});assert.deepEqual(seasonWeekFromFilename("season-9-week-12 results.csv"),{season:9,week:12})})
test("rank is optional and scores remain authoritative",()=>{const result=parseHistoricalKwtRows([{Player:"INDY","Easy Code":"ILE",Easy:"-22","Hard Code":"ILH",Hard:"-16",Total:"-38"}],"kwt14w4.csv");assert.equal(result.errors.length,0);assert.equal(result.rows[0].rank,null);assert.equal(result.rows[0].totalScore,-38)})
test("supported historical ranks normalize",()=>{assert.equal(normalizeHistoricalKwtRank("Semi Pro"),"Semi-Pro");assert.equal(normalizeHistoricalKwtRank("Elite"),"Elite");assert.equal(normalizeHistoricalKwtRank("A"),"Amateur");assert.equal(normalizeHistoricalKwtRank("old code"),null)})
test("website course codes and AMA rank normalize through the parser",()=>{const result=parseHistoricalKwtRows([{Player:"Legacy Name",EasyCode:"LLE",Easy:"-20",HardCode:"LLH",Hard:"-18",Total:"-38",Rank:"AMA"}],"KWT10W01.csv");assert.equal(result.errors.length,0);assert.equal(result.warnings.length,0);assert.equal(result.rows[0].easyCode,"LLE");assert.equal(result.rows[0].rank,"Amateur")})
test("aliases and duplicate protection work",()=>{const source={PLAYER_NAME:"El Jorge",Season:"8",Week:"2",EasyCourse:"HWE",EasyScore:"-20",HardCourse:"HWH",HardScore:"-15",Combined:"-35",Division:"Pro",Pos:"3"};const result=parseHistoricalKwtRows([source,source],"scores.csv");assert.equal(result.rows.length,1);assert.equal(result.duplicateRows,1);assert.equal(result.rows[0].rank,"Pro")})
test("a conflicting supplied total blocks the row",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"ILE",Easy:"-22",HardCode:"ILH",Hard:"-16",Total:"-37"}],"kwt14w4.csv");assert.equal(result.rows.length,0);assert.match(result.errors[0],/does not equal/)})
test("conflicting duplicate logical rows block the source",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"ILE",Easy:"-22",HardCode:"ILH",Hard:"-16"},{Player:"INDY",EasyCode:"ILE",Easy:"-21",HardCode:"ILH",Hard:"-16"}],"kwt14w4.csv");assert.equal(result.rows.length,1);assert.match(result.errors[0],/conflicting duplicate/)})
test("unknown course codes block the source",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"BAD",Easy:"-22",HardCode:"ILH",Hard:"-16"}],"kwt14w4.csv");assert.equal(result.rows.length,0);assert.match(result.errors[0],/unsupported KWT course/)})
test("malformed optional numeric facts block the source",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"ILE",Easy:"-22",HardCode:"ILH",Hard:"-16",Total:"-38",Pos:"third"}],"kwt14w4.csv");assert.equal(result.rows.length,0);assert.match(result.errors[0],/placement must be/)})
test("Apply is admin-only, identity-bound, idempotent, and preserves optional rank",()=>{const sql=readFileSync(new URL("../../../historical_kwt_import_foundation.sql",import.meta.url),"utf8");assert.match(sql,/is_current_user_site_admin\(\)/);assert.match(sql,/canonical_player_id uuid not null references public\.players/);assert.match(sql,/source_sha256 text not null unique/);assert.match(sql,/historical_rank text null/);assert.match(sql,/total_score = easy_score \+ hard_score/);assert.match(sql,/commit_historical_kwt_preview/);assert.match(sql,/select count\(\*\)::integer into scorecard_count\s+from public\.historical_kwt_scorecards as score\s+where score\.historical_kwt_import_id = v_import\.id/);assert.match(sql,/from public\.historical_kwt_scorecards as score\s+where score\.source_fingerprint=v_row->>'rowKey'\s+and score\.historical_kwt_import_id<>v_import\.id/);assert.match(sql,/where public\.resolve_canonical_player_id\(score\.canonical_player_id\)\s*=\s*public\.resolve_canonical_player_id\(p_player_id\)/);assert.doesNotMatch(sql,/where score\.canonical_player_id=public\.resolve_canonical_player_id\(p_player_id\)/)})
test("website rank cleanup is one-time, scoped, and score-preserving",()=>{const sql=readFileSync(new URL("../../../historical_kwt_website_rank_cleanup.sql",import.meta.url),"utf8");assert.match(sql,/historical_kwt_website_rank_cleanup_runs/);assert.match(sql,/v_website_source_shas\s+text\[\]/);assert.match(sql,/source_import\.source_sha256\s*=\s*any\(v_website_source_shas\)/);assert.match(sql,/set historical_rank = null,\s+raw_historical_rank = null/);assert.match(sql,/score\.historical_kwt_import_id/);assert.doesNotMatch(sql,/set\s+[^;]*(easy_score|hard_score|total_score|season_number|week_number|placement)/i);assert.match(sql,/already completed; no rows changed/)})
