import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import {normalizeHistoricalKwtRank,parseHistoricalKwtRows,seasonWeekFromFilename} from "./kwtAdapter.ts"

test("season and week are recovered from historical KWT filenames",()=>{assert.deepEqual(seasonWeekFromFilename("KWT11W03.csv"),{season:11,week:3});assert.deepEqual(seasonWeekFromFilename("season-9-week-12 results.csv"),{season:9,week:12})})
test("rank is optional and scores remain authoritative",()=>{const result=parseHistoricalKwtRows([{Player:"INDY","Easy Code":"ILE",Easy:"-22","Hard Code":"ILH",Hard:"-16",Total:"-38"}],"kwt14w4.csv");assert.equal(result.errors.length,0);assert.equal(result.rows[0].rank,null);assert.equal(result.rows[0].totalScore,-38)})
test("supported historical ranks normalize",()=>{assert.equal(normalizeHistoricalKwtRank("Semi Pro"),"Semi-Pro");assert.equal(normalizeHistoricalKwtRank("Elite"),"Elite");assert.equal(normalizeHistoricalKwtRank("A"),"Amateur");assert.equal(normalizeHistoricalKwtRank("old code"),null)})
test("aliases and duplicate protection work",()=>{const source={PLAYER_NAME:"El Jorge",Season:"8",Week:"2",EasyCourse:"HWE",EasyScore:"-20",HardCourse:"HWH",HardScore:"-15",Combined:"-35",Division:"Pro",Pos:"3"};const result=parseHistoricalKwtRows([source,source],"scores.csv");assert.equal(result.rows.length,1);assert.equal(result.duplicateRows,1);assert.equal(result.rows[0].rank,"Pro")})
test("a conflicting supplied total blocks the row",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"ILE",Easy:"-22",HardCode:"ILH",Hard:"-16",Total:"-37"}],"kwt14w4.csv");assert.equal(result.rows.length,0);assert.match(result.errors[0],/does not equal/)})
test("conflicting duplicate logical rows block the source",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"ILE",Easy:"-22",HardCode:"ILH",Hard:"-16"},{Player:"INDY",EasyCode:"ILE",Easy:"-21",HardCode:"ILH",Hard:"-16"}],"kwt14w4.csv");assert.equal(result.rows.length,1);assert.match(result.errors[0],/conflicting duplicate/)})
test("unknown course codes block the source",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"BAD",Easy:"-22",HardCode:"ILH",Hard:"-16"}],"kwt14w4.csv");assert.equal(result.rows.length,0);assert.match(result.errors[0],/unsupported KWT course/)})
test("malformed optional numeric facts block the source",()=>{const result=parseHistoricalKwtRows([{Player:"INDY",EasyCode:"ILE",Easy:"-22",HardCode:"ILH",Hard:"-16",Total:"-38",Pos:"third"}],"kwt14w4.csv");assert.equal(result.rows.length,0);assert.match(result.errors[0],/placement must be/)})
test("Apply is admin-only, identity-bound, idempotent, and preserves optional rank",()=>{const sql=readFileSync(new URL("../../../historical_kwt_import_foundation.sql",import.meta.url),"utf8");assert.match(sql,/is_current_user_site_admin\(\)/);assert.match(sql,/canonical_player_id uuid not null references public\.players/);assert.match(sql,/source_sha256 text not null unique/);assert.match(sql,/historical_rank text null/);assert.match(sql,/total_score = easy_score \+ hard_score/);assert.match(sql,/commit_historical_kwt_preview/)})
