"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { formatMajorLocalTime, formatMajorToPar, majorRoundDayLabel, type MajorEvent, type MajorPlayDay, type MajorPlayerScorecard } from "@/lib/majors"
import { supabase } from "@/lib/supabase"

export default function MajorVerificationPage(){
 const [events,setEvents]=useState<MajorEvent[]>([]),[days,setDays]=useState<MajorPlayDay[]>([]),[cards,setCards]=useState<MajorPlayerScorecard[]>([]),[entryCount,setEntryCount]=useState(0)
 const [eventId,setEventId]=useState(""),[dayId,setDayId]=useState(""),[status,setStatus]=useState("submitted"),[slot,setSlot]=useState(""),[room,setRoom]=useState(""),[search,setSearch]=useState(""),[message,setMessage]=useState("")
 const load=useCallback(async()=>{const [e,d]=await Promise.all([supabase.from("major_events").select("*").order("slug"),supabase.from("major_play_days").select("*").order("day_number")]);setEvents((e.data as MajorEvent[])||[]);setDays((d.data as MajorPlayDay[])||[]);setEventId(x=>x||(e.data?.[0]?.id as string)||"");setMessage(e.error?.message||d.error?.message||"")},[])
 // Initial authenticated Supabase synchronization.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!eventId)return;void(async()=>{const [r,e]=await Promise.all([supabase.rpc("get_major_scorecard_verification_queue",{p_major_event_id:eventId}),supabase.from("major_entries").select("id",{count:"exact",head:true}).eq("major_event_id",eventId).in("status",["registered","confirmed"])]);setCards((r.data as MajorPlayerScorecard[])||[]);setEntryCount(e.count||0);setMessage(r.error?.message||e.error?.message||"")})()},[eventId])
 const visible=useMemo(()=>cards.filter(c=>(!dayId||c.play_day_id===dayId)&&(!status||c.status===status)&&(!slot||c.slot_starts_at===slot)&&(!room||c.room_label===room)&&c.player_screen_name_snapshot.toLowerCase().includes(search.toLowerCase())),[cards,dayId,status,slot,room,search])
 const eventDays=days.filter(d=>d.major_event_id===eventId),submitted=cards.filter(c=>c.major_event_id===eventId&&c.status==="submitted").length,verified=cards.filter(c=>c.major_event_id===eventId&&c.status==="verified").length
 async function refreshCards(){if(!eventId)return;const r=await supabase.rpc("get_major_scorecard_verification_queue",{p_major_event_id:eventId});setCards((r.data as MajorPlayerScorecard[])||[])}
 async function action(name:"verify_major_scorecard"|"reopen_major_scorecard",id:string){const notes=window.prompt(name.startsWith("verify")?"Optional verification notes":"Reason for reopening")||"";const r=await supabase.rpc(name,{p_scorecard_id:id,p_notes:notes});setMessage(r.error?.message||"Saved.");if(!r.error)await refreshCards()}
 async function toggle(day:MajorPlayDay){const r=await supabase.rpc("set_major_round_scoring_state",{p_play_day_id:day.id,p_is_open:!(day as MajorPlayDay & {scoring_entry_open?:boolean}).scoring_entry_open});setMessage(r.error?.message||"Round entry state updated.");if(!r.error)await load()}
 async function finalize(day:MajorPlayDay){if(!confirm("Finalize this round and preserve its historical standings snapshot?"))return;const r=await supabase.rpc("finalize_major_scoring_round",{p_play_day_id:day.id});setMessage(r.error?.message||"Round finalized and snapshot preserved.");if(!r.error)await load()}
 return <main style={page}><div style={shell}><Link href="/admin/majors/scoring">← Major scoring</Link><h1>Verify Major Results</h1><p style={muted}>Players submit complete 18-hole cards. Admins verify the final total, with full holes available for inspection.</p>
 <section style={summary}><strong>Submitted: {submitted+verified}</strong><strong style={pending}>Awaiting verification: {submitted}</strong><strong style={official}>Verified: {verified}</strong><strong>Missing: {Math.max(0,entryCount-new Set(cards.map(c=>c.entry_id)).size)}</strong></section>
 <div style={filters}><select value={eventId} onChange={e=>{setEventId(e.target.value);setDayId("")}}>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><select value={dayId} onChange={e=>setDayId(e.target.value)}><option value="">All rounds</option>{eventDays.map(d=><option key={d.id} value={d.id}>{majorRoundDayLabel(d.day_number)}</option>)}</select><select value={slot} onChange={e=>setSlot(e.target.value)}><option value="">All slots</option>{[...new Set(cards.map(c=>c.slot_starts_at).filter(Boolean))].map(x=><option key={x!} value={x!}>{formatMajorLocalTime(x!)}</option>)}</select><select value={room} onChange={e=>setRoom(e.target.value)}><option value="">All rooms</option>{[...new Set(cards.map(c=>c.room_label).filter(Boolean))].map(x=><option key={x!} value={x!}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All states</option><option value="submitted">Awaiting Verification</option><option value="verified">Verified</option><option value="draft">Draft</option><option value="reopened">Reopened</option></select><input placeholder="Search player" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <section style={roundControls}>{eventDays.map(d=>{const open=(d as MajorPlayDay&{scoring_entry_open?:boolean}).scoring_entry_open;return <article key={d.id} style={card}><strong>{majorRoundDayLabel(d.day_number)}</strong><span>{open?"Player entry open":"Player entry closed"}</span><button onClick={()=>toggle(d)}>{open?"Close entry":"Open entry"}</button><button onClick={()=>finalize(d)}>Finalize round</button></article>})}</section>
 <div style={list}>{visible.map(c=><details key={c.id} style={card}><summary style={row}><strong>{c.player_screen_name_snapshot}</strong><span>{c.room_label||"Room pending"}</span><span>{c.slot_starts_at?formatMajorLocalTime(c.slot_starts_at):"Slot pending"}</span><strong>{c.total_strokes??c.holes.reduce((s,h)=>s+h.strokes,0)} · {formatMajorToPar(c.score_to_par??c.holes.reduce((s,h)=>s+h.strokes-h.par,0))}</strong><span style={c.status==="verified"?official:pending}>{c.status}</span></summary><div style={holes}>{c.holes.map(h=><span key={h.hole_number}>H{h.hole_number}: {h.strokes} <small>(par {h.par})</small></span>)}</div><p>Submitted: {c.submitted_at?new Date(c.submitted_at).toLocaleString():"Not submitted"} · Verified: {c.verified_at?new Date(c.verified_at).toLocaleString():"Not verified"}</p><div style={actions}>{c.status==="submitted"&&<button onClick={()=>action("verify_major_scorecard",c.id)}>Verify score</button>}{["submitted","verified"].includes(c.status)&&<button onClick={()=>action("reopen_major_scorecard",c.id)}>Reopen for correction</button>}</div></details>)}</div>{message&&<p>{message}</p>}
 </div></main>}
const page:React.CSSProperties={minHeight:"100vh",padding:20,background:"#09090b",color:"white"},shell:React.CSSProperties={maxWidth:1300,margin:"auto"},muted:React.CSSProperties={color:"#a1a1aa"},summary:React.CSSProperties={display:"flex",gap:20,flexWrap:"wrap",padding:16,background:"#18181b",borderRadius:12},pending:React.CSSProperties={color:"#f472b6"},official:React.CSSProperties={color:"#4ade80"},filters:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,margin:"16px 0"},roundControls:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10},list:React.CSSProperties={display:"grid",gap:10,marginTop:18},card:React.CSSProperties={padding:14,border:"1px solid #3f3f46",borderRadius:10,background:"#18181b"},row:React.CSSProperties={display:"grid",gridTemplateColumns:"2fr repeat(4,1fr)",gap:10,cursor:"pointer"},holes:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:7,padding:"15px 0"},actions:React.CSSProperties={display:"flex",gap:8}
