$ErrorActionPreference='Stop'
$o='https://dqvo64m7q9ujvqa-wmgt23ai.adb.us-ashburn-1.oraclecloudapps.com';$d=Split-Path -Parent $MyInvocation.MyCommand.Path;$u0=$o+'/ords/r/wmgt/monthly/home';$e=[Text.UTF8Encoding]::new($false)
function GetSha($p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash}
function Capture($n){$w=New-Object Microsoft.PowerShell.Commands.WebRequestSession;$u=$u0;$r=$null;$title='';for($i=0;$i-lt20;$i++){$r=Invoke-WebRequest $u -WebSession $w -UseBasicParsing -TimeoutSec 30;$title=[regex]::Match($r.Content,'<h1[^>]+class="monthlyHero__title"[^>]*>(.*?)</h1>',[Text.RegularExpressions.RegexOptions]::Singleline).Groups[1].Value -replace '<[^>]+>','' -replace '\s+',' ';$title=$title.Trim();if($title-eq'2025 August'){break};$x=[regex]::Match($r.Content,'<a[^>]+href="([^"]+)"[^>]+title="Previous"').Groups[1].Value;$x=[System.Net.WebUtility]::HtmlDecode($x);$u=if($x.StartsWith('/')){$o+$x}else{$x}};if($title-ne'2025 August'){throw 'Could not reach target period'};$ss=[regex]::Match($r.Content,'APP_SESSION:\s*"([^"]+)"').Groups[1].Value;$r=Invoke-WebRequest "$o/ords/f?p=500:1:$ss:::1:P1_LEAGUE_ID:22" -WebSession $w -UseBasicParsing -TimeoutSec 30;$h=$r.Content;$a=$h.IndexOf('aria-label="&#x20;&#x20;Atlantis"');$j=$h.IndexOf('<table class="t-Report-report"',$a);$k=$h.IndexOf('</table>',$j);$table=$h.Substring($j,$k-$j+8);$block=$table;$row=[regex]::Match($table,'(?s)<tr>.*?data-id="8108".*?</tr>').Value;$score=[regex]::Match($row,'headers="SCORE">([^<]*)').Groups[1].Value.Trim();$slug="repro-$n-period-221-division-22";$hp=Join-Path $d ($slug+'.html');$tp=Join-Path $d ($slug+'.txt');$jp=Join-Path $d ($slug+'.json');[IO.File]::WriteAllText($hp,$h,$e);[IO.File]::WriteAllText($tp,(($block-replace '(?s)<script.*?</script>',''-replace '(?s)<style.*?</style>',''-replace '<[^>]+>',' '-replace '\s+',' ').Trim()),$e);$z=[pscustomobject]@{repetition=$n;period='2025 August';period_id=221;division='Elite';division_id=22;course='Atlantis';source_player_name='PETERK9FLORIDA';source_player_id=8108;score_text=$score;leader_rows=([regex]::Matches($h,'id="report_table_leagueLeaders"').Count);course_tables=([regex]::Matches($h,'class="t-Region scoreRegion').Count);html_sha256=(GetSha $hp);text_sha256=(GetSha $tp);html_file=$slug+'.html';text_file=$slug+'.txt';session_state='not stored'};[IO.File]::WriteAllText($jp,($z|ConvertTo-Json -Depth 8),$e);$z}
$a=Capture 1;$b=Capture 2;$c=Capture 3;@($a,$b,$c)|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $d 'reproduction-summary.json') -Encoding utf8;@('repetition`tperiod`tperiod_id`tdivision`tdivision_id`tcourse`tsource_player_name`tsource_player_id`tscore_text`tleader_rows`tcourse_tables`thtml_sha256`ttext_sha256`thtml_file`ttext_file')+@($a,$b,$c|ForEach-Object{"$($_.repetition)`t$($_.period)`t$($_.period_id)`t$($_.division)`t$($_.division_id)`t$($_.course)`t$($_.source_player_name)`t$($_.source_player_id)`t$($_.score_text)`t$($_.leader_rows)`t$($_.course_tables)`t$($_.html_sha256)`t$($_.text_sha256)`t$($_.html_file)`t$($_.text_file)"})|Set-Content -LiteralPath (Join-Path $d 'reproduction.tsv') -Encoding utf8




