import { strict as assert } from "node:assert"
import { readFileSync } from "node:fs"
import { test } from "node:test"

const root = new URL("../../", import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), "utf8")

test("admin review hotfix keeps review actions, mode selection, and private history in one queue", () => {
  const api = read("app/api/admin/course-challenges/route.ts")
  const queue = read("components/admin/course-challenges/CourseChallengeReviewQueue.tsx")
  assert.match(api, /return_to_review/)
  assert.match(api, /p_admin_verified_game_mode/)
  assert.match(api, /course_challenge_submission_review_events/)
  assert.match(api, /course_challenge_submissions.*proof_image_sha256/)
  assert.match(queue, /showRejectedSection/)
  assert.match(queue, /PAST CARDS/)
  assert.match(queue, /possibleDuplicate/)
  assert.match(queue, /GAME MODE/)
  assert.match(queue, />SOLO</)
  assert.match(queue, />MULTIPLAYER</)
  assert.match(queue, /adminVerifiedGameMode/)
  assert.match(queue, /courseChallengeGameModeError/)
  assert.match(queue, /Your selection is saved immediately and rechecked on approval/)
  assert.match(queue, /action: "verify_game_mode"/)
  assert.match(queue, /adminVerifiedGameMode: payload\.gameMode \|\| mode/)
  assert.doesNotMatch(queue, /const lockedMode/)
  assert.doesNotMatch(queue, /: "multiplayer"/)
  assert.match(api, /normalizeCourseChallengeGameMode\(body\.gameMode\)/)
  assert.match(api, /body\.action === "verify_game_mode"/)
  assert.match(api, /admin_verified_game_mode: verifiedGameMode/)
  assert.match(api, /admin_game_mode_verified_by: authorization\.user\?\.id \|\| null/)
  assert.match(api, /admin_game_mode_verified_at: new Date\(\)\.toISOString\(\)/)
  assert.match(api, /p_admin_verified_game_mode: verifiedGameMode/)
  assert.doesNotMatch(api, /body\.gameMode \|\| \(challengeKey/)
})

test("active review queue excludes rejected and approved cards while rejected cards stay separate", () => {
  const api = read("app/api/admin/course-challenges/route.ts")
  const queue = read("components/admin/course-challenges/CourseChallengeReviewQueue.tsx")
  const page = read("app/admin/course-challenges/page.tsx")
  const getHandler = api.match(/export async function GET\([\s\S]*?\n}\n\nasync function signProof/)?.[0]

  assert.match(api, /const statuses = params\.get\("status"\) === "rejected" \? \["rejected"\] : \["pending", "needs_review"\]/)
  assert.doesNotMatch(api, /includeRejected/)
  assert.match(api, /pendingQuery[\s\S]*\.in\("status", \["pending", "needs_review"\]\)/)
  assert.match(queue, /fetch\("\/api\/admin\/course-challenges", \{ cache: "no-store" \}\)/)
  assert.match(queue, /fetch\("\/api\/admin\/course-challenges\?status=rejected", \{ cache: "no-store" \}\)/)
  assert.match(queue, /showRejectedSection/)
  assert.match(queue, /REJECTED CARDS/)
  assert.match(queue, /rejectedSubmissions\.length/)
  assert.match(queue, /onToggle=/)
  assert.match(queue, /rejectedLoaded/)
  assert.match(queue, /if \(rejectedLoaded\) await loadRejected\(\)/)
  assert.match(queue, /return_to_review/)
  assert.match(page, /<CourseChallengeReviewQueue showRejectedSection \/>/)
  assert.ok(getHandler, "the admin GET handler must be present")
  assert.doesNotMatch(getHandler || "", /\.update\(|\.delete\(|\.insert\(/)

  const statusesFor = (status: string | null) => status === "rejected" ? ["rejected"] : ["pending", "needs_review"]
  assert.deepEqual(statusesFor(null), ["pending", "needs_review"])
  assert.deepEqual(statusesFor("rejected"), ["rejected"])
  assert.deepEqual(statusesFor("approved"), ["pending", "needs_review"])
})

test("admin review migration is additive and retry-safe", () => {
  const sql = read("course_challenges_admin_review_hotfix.sql")
  assert.match(sql, /add column if not exists/i)
  assert.match(sql, /unique \(submission_id, notification_kind\)/i)
  assert.match(sql, /for update/i)
  assert.match(sql, /return_course_challenge_submission_to_review/i)
  assert.match(sql, /submission_id uuid not null references public\.course_challenge_submissions/i)
  assert.doesNotMatch(sql, /delete from public\.course_challenge_submissions/i)
})

test("review desk and site-wide alert use the same protected queue", () => {
  const desk = read("app/admin/course-challenges/review-desk/page.tsx")
  const alert = read("components/admin/CourseChallengePendingAlert.tsx")
  const submissions = read("app/api/course-challenges/submissions/route.ts")
  assert.match(desk, /CourseChallengeReviewQueue/)
  assert.match(alert, /\/api\/admin\/course-challenges\?summary=1/)
  assert.match(alert, /course-challenge-dismissed-latest/)
  assert.match(alert, /CC REVIEWS/)
  assert.match(submissions, /DISCORD_WEBHOOK_COURSE_CHALLENGE_REVIEW/)
  assert.match(submissions, /notification_kind: "discord_review_needed"/)
})

test("duplicate evidence is track-aware and verified Level cards receive automatic idempotent Ace credit", () => {
  const api = read("app/api/admin/course-challenges/route.ts")
  const queue = read("components/admin/course-challenges/CourseChallengeReviewQueue.tsx")
  const submissions = read("app/api/course-challenges/submissions/route.ts")
  assert.match(queue, /SAME-TRACK DUPLICATE — APPROVAL BLOCKED/)
  assert.match(queue, /ALLOWED CROSS-TRACK USE/)
  assert.match(queue, /credited automatically/)
  assert.match(queue, /courseChallengeGameModeError/)
  assert.doesNotMatch(queue, /type="checkbox"/)
  assert.doesNotMatch(api, /body\.countTowardAceTrack/)
  assert.match(api, /classifyDuplicateCard/)
  assert.match(api, /applyAceCrossCredit/)
  assert.match(api, /aceCrossCreditRows/)
  assert.match(api, /ignoreDuplicates: true/)
  assert.match(api, /unique ace holes/)
  assert.match(submissions, /aceStageAtSubmission|ace_stage_number: challengeKey === "ace" \? requestedAceStage : aceState\.nextStage\?\.stage/)
})

test("Ace review cards hide game mode and approval ignores stored mode values", () => {
  const api = read("app/api/admin/course-challenges/route.ts")
  const queue = read("components/admin/course-challenges/CourseChallengeReviewQueue.tsx")
  const gameMode = read("lib/courseChallenges/gameMode.ts")
  assert.match(queue, /submission\.challengeKey === "ace" \? null/)
  assert.match(queue, /submission\.challengeKey !== "ace" && <fieldset/)
  assert.match(queue, /submission\.challengeKey !== "ace" && <p style=\{muted\}>Stored Game Mode/)
  assert.match(api, /challenge_key === "ace"\) return Response\.json\(\{ error: "Ace Track does not use game-mode verification\."/)
  assert.match(api, /challengeKey === "ace" \? null : normalizeCourseChallengeGameMode\(body\.gameMode\)/)
  assert.match(gameMode, /if \(challengeKey === "ace"\) return null/)
})

test("GOLDENBRETT pending Ace Wader can proceed without Solo or Multiplayer", () => {
  const api = read("app/api/admin/course-challenges/route.ts")
  const sql = read("course_challenges_admin_review_hotfix.sql")
  const guard = read("course_challenges_self_approval_guard.sql")
  const book = read("components/course-challenges/CourseChallengeBook.tsx")
  const guide = read("components/course-challenges/CourseChallengesGuide.tsx")
  for (const source of [sql, guard]) {
    assert.match(source, /if v_submission\.challenge_key = 'ace' then/)
    assert.match(source, /v_mode := null/)
    assert.match(source, /challenge_key = 'prestige'/)
    assert.doesNotMatch(source, /v_submission\.challenge_key = 'ace' or v_submission\.level_number >= 3/)
    assert.match(source, /case when v_submission\.challenge_key = 'ace' then v_submission\.admin_verified_game_mode/)
  }
  assert.match(api, /challengeKey === "ace" \? null : normalizeCourseChallengeGameMode/)
  assert.doesNotMatch(book, /Levels 3–5, Course Pro, Course Master, and Ace use the established Multiplayer review rule/)
  assert.match(book, /Levels 3–5, Course Pro, and Course Master use the established Multiplayer review rule/)
  assert.doesNotMatch(guide, /Ace cards follow the established Multiplayer review rule/)
  assert.match(guide, /Ace cards are evaluated only by their unique-hole requirements/)
})
