import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import { departureConfirmationDecision, privateDepartureMessage, reconciliationCandidates, resolveDeparturePlayer, type DeparturePlayer } from "./discordDeparture.ts"

const player: DeparturePlayer = { id: "canonical-uuid", screenName: "Krys Name", discordId: "123", status: "active", isMemorial: false }
test("departure resolves only exact Discord ID to canonical player", () => { assert.equal(resolveDeparturePlayer("123", [player]).player?.id, "canonical-uuid"); assert.equal(resolveDeparturePlayer("999", [player]).status, "unresolved"); assert.equal(resolveDeparturePlayer("123", [player, { ...player, id: "duplicate" }]).status, "ambiguous") })
test("private message prioritizes Krys and last server identities", () => { const message = privateDepartureMessage(player, { discordId: "123", serverDisplayName: "Known Nickname", discordUsername: "globalname" }); assert.equal(message.visibility, "admin_only"); assert.deepEqual(message.fields.slice(0, 3).map((field) => field.value), ["Krys Name", "Known Nickname", "globalname / 123"]); assert.deepEqual(message.actions, ["archive_player", "mark_inactive", "ignore"]) })
test("leave event alone never authorizes archive", () => { assert.equal(departureConfirmationDecision({ authorizedAdmin: false, action: "archive_player", currentlyGuildMember: false }).result, "unauthorized") })
test("live membership recheck cancels archive after rejoin", () => { const result = departureConfirmationDecision({ authorizedAdmin: true, action: "archive_player", currentlyGuildMember: true }); assert.equal(result.allowed, false); assert.equal(result.message, "Archive cancelled — this player is currently a member of the server.") })
test("authorized archive proceeds only after confirmed absence", () => { assert.equal(departureConfirmationDecision({ authorizedAdmin: true, action: "archive_player", currentlyGuildMember: false }).result, "archive_confirmed") })
test("ignore changes no status", () => { assert.equal(departureConfirmationDecision({ authorizedAdmin: true, action: "ignore", currentlyGuildMember: false }).result, "ignored") })
test("reconciliation privately suggests absent active linked players without mass archive", () => { const results = reconciliationCandidates([player, { ...player, id: "present", discordId: "456", screenName: "Present" }, { ...player, id: "archived", discordId: "789", status: "archived" }], new Set(["456"])); assert.deepEqual(results.map((row) => row.id), ["canonical-uuid"]) })
test("bot and website share one protected three-state canonical status RPC", () => { const sql = readFileSync(new URL("../discord_departure_archive_workflow.sql", import.meta.url), "utf8"); const page = readFileSync(new URL("../app/admin/players/page.tsx", import.meta.url), "utf8"); assert.match(sql, /function public\.set_site_player_status/); assert.match(sql, /select public\.set_site_player_status\(v_player\.id,v_new_status,'discord_departure'/); assert.match(page, /rpc\("set_site_player_status"/); assert.match(page, /const PLAYER_STATUSES = \["active", "inactive", "archived"\]/); assert.doesNotMatch(page, /const PLAYER_STATUSES = .*memorial/) })
test("website status confirmation explains consequences and Memorial remains separate", () => { const page = readFileSync(new URL("../app/admin/players/page.tsx", import.meta.url), "utf8"); assert.match(page, /Remains on All-Time boards/); assert.match(page, /Records cleanup waits for a safe Climbers finalization boundary/); assert.match(page, /Memorial is managed separately/); assert.match(page, /statusConfirmed/) })
