import assert from "node:assert/strict"
import test from "node:test"
import { activeLeaderboardAfterArchivedCleanup, calendarMonthCutoff, climbersStandings, evaluateSubmission, finalizedWinners, replaySubmissions, yearToDatePoints, type BoardScore, type ScoreSubmission } from "../../lib/all-time/climbers.ts"

const season = [{ id: "s7", startsAt: "2026-08-01T00:00:00Z", endsAt: "2026-08-15T00:00:00Z" }]
const base: ScoreSubmission = { id: "score", playerId: "krys", courseId: "AME", courseKind: "individual", courseActive: true, score: 32, scorecardAt: "2026-08-02T12:00:00Z", submittedAt: "2026-08-03T12:00:00Z", source: "current_submission", serverMember: true, properGame: true, witnessCompleted18: true }
const evaluate = (overrides: Partial<ScoreSubmission> = {}, board: BoardScore[] = []) => evaluateSubmission({ ...base, ...overrides }, board, season, "UTC")

test("first score establishes PB and earns zero", () => { const result = evaluate(); assert.equal(result.pbResult, "first"); assert.equal(result.newPb, 32); assert.equal(result.climbersPoints, 0); assert.equal(result.createsClimbersEvent, false) })
test("better PB with nobody passed stores a zero-point event", () => { const result = evaluate({}, [{ playerId: "krys", score: 35 }, { playerId: "leader", score: 30 }]); assert.equal(result.pbResult, "better"); assert.equal(result.createsClimbersEvent, true); assert.equal(result.climbersPoints, 0) })
test("better PB counts exact people strictly passed", () => { const result = evaluate({}, [{ playerId: "krys", score: 40 }, { playerId: "a", score: 39 }, { playerId: "b", score: 36 }, { playerId: "c", score: 32 }, { playerId: "d", score: 31 }]); assert.deepEqual(result.passedPlayerIds, ["a", "b"]); assert.equal(result.climbersPoints, 2) })
test("new tie is not a pass", () => { const result = evaluate({ score: 36 }, [{ playerId: "krys", score: 40 }, { playerId: "a", score: 36 }]); assert.equal(result.climbersPoints, 0) })
test("equal and worse scores do not change PB or climb", () => { assert.equal(evaluate({ score: 35 }, [{ playerId: "krys", score: 35 }]).pbResult, "equal"); const worse = evaluate({ score: 36 }, [{ playerId: "krys", score: 35 }]); assert.equal(worse.pbResult, "worse"); assert.equal(worse.newPb, 35); assert.equal(worse.climbersPoints, 0) })
test("Easy and Hard individual courses count; combined courses never count", () => { const board = [{ playerId: "krys", score: 40 }, { playerId: "a", score: 35 }]; assert.equal(evaluate({ courseId: "E", score: 34 }, board).climbersPoints, 1); assert.equal(evaluate({ courseId: "H", score: 34 }, board).climbersPoints, 1); assert.equal(evaluate({ courseKind: "combined", score: 34 }, board).climbersPoints, 0) })
test("historical imports may improve PB but never award Climbers", () => { const result = evaluate({ source: "historical_import", score: 30, appliedAt: "2026-08-02T00:00:00Z" }, [{ playerId: "krys", score: 40 }, { playerId: "a", score: 35 }]); assert.equal(result.pbResult, "better"); assert.equal(result.newPb, 30); assert.equal(result.seasonId, null); assert.equal(result.climbersPoints, 0) })
test("current improvement starts from historical-established baseline", () => { const replay = replaySubmissions(new Map([["AME", [{ playerId: "krys", score: 40 }, { playerId: "a", score: 34 }, { playerId: "b", score: 29 }]]]), [{ ...base, id: "historic", source: "historical_import", score: 33, appliedAt: "2026-08-02T00:00:00Z" }, { ...base, id: "current", score: 28 }], season, "UTC"); assert.equal(replay.evaluations[0].climbersPoints, 0); assert.equal(replay.evaluations[1].previousPb, 33); assert.deepEqual(replay.evaluations[1].passedPlayerIds, ["b"]) })
test("later historical baseline changes preserve earlier earned Climbers and affect only later submissions", () => { const replay = replaySubmissions(new Map([["AME", [{ playerId: "krys", score: 40 }, { playerId: "a", score: 38 }, { playerId: "b", score: 34 }, { playerId: "c", score: 30 }]]]), [{ ...base, id: "earned-before-import", score: 37, submittedAt: "2026-08-02T13:00:00Z" }, { ...base, id: "historical-baseline", source: "historical_import", score: 33, appliedAt: "2026-08-05T00:00:00Z" }, { ...base, id: "earned-after-import", score: 29, submittedAt: "2026-08-06T00:00:00Z" }], season, "UTC"); assert.deepEqual(replay.evaluations.map((row) => row.submissionId), ["earned-before-import", "historical-baseline", "earned-after-import"]); assert.deepEqual(replay.evaluations.map((row) => row.climbersPoints), [1, 0, 1]); assert.equal(replay.evaluations[2].previousPb, 33) })
test("Discord post chronology wins over admin entry ordering", () => { const replay = replaySubmissions(new Map([["AME", [{ playerId: "krys", score: 40 }, { playerId: "a", score: 37 }, { playerId: "b", score: 34 }]]]), [{ ...base, id: "later", score: 33, submittedAt: "2026-08-04T00:00:00Z" }, { ...base, id: "earlier", score: 36, submittedAt: "2026-08-03T00:00:00Z" }], season, "UTC"); assert.deepEqual(replay.evaluations.map((row) => row.submissionId), ["earlier", "later"]); assert.deepEqual(replay.evaluations.map((row) => row.climbersPoints), [1, 1]) })
test("multiple improvements and a repeated opponent pass both count", () => { const first = replaySubmissions(new Map([["AME", [{ playerId: "krys", score: 40 }, { playerId: "alex", score: 38 }]]]), [{ ...base, id: "one", score: 37 }, { ...base, id: "two", score: 35, submittedAt: "2026-08-04T00:00:00Z" }], season, "UTC"); assert.equal(climbersStandings(first.evaluations, "s7")[0].points, 1); const second = evaluate({ id: "three", score: 33 }, [{ playerId: "krys", score: 35 }, { playerId: "alex", score: 34 }]); assert.equal(second.climbersPoints, 1) })
test("correction reversal removes fake points during deterministic replay", () => { const submissions = [{ ...base, id: "wrong", score: 30 }, { ...base, id: "corrected", score: 36, submittedAt: "2026-08-04T00:00:00Z", correctedBySubmissionId: "wrong" }]; const replay = replaySubmissions(new Map([["AME", [{ playerId: "krys", score: 40 }, { playerId: "a", score: 35 }]]]), submissions, season, "UTC"); assert.deepEqual(replay.evaluations.map((row) => row.submissionId), ["corrected"]); assert.equal(replay.evaluations[0].climbersPoints, 0) })
test("calendar-month cutoff accepts same prior date and clamps short months", () => { assert.equal(calendarMonthCutoff("2026-11-02T12:00:00Z", "UTC"), "2026-10-02T12:00:00.000Z"); assert.equal(evaluate({ scorecardAt: "2026-07-03T11:59:59Z", submittedAt: "2026-08-03T12:00:00Z" }).eligible, false); assert.equal(calendarMonthCutoff("2026-03-31T12:00:00Z", "UTC"), "2026-02-28T12:00:00.000Z") })
test("timezone cutoff preserves configured local wall time across DST", () => { assert.equal(calendarMonthCutoff("2026-04-15T16:00:00Z", "America/New_York"), "2026-03-15T16:00:00.000Z") })
test("invalid course and eligibility evidence reject submission", () => { const result = evaluate({ courseActive: false, serverMember: false, properGame: false, witnessCompleted18: false }); assert.equal(result.eligible, false); assert.equal(result.rejectionReasons.length, 4) })
test("season finalization preserves tied winners and YTD derives finalized totals", () => { assert.deepEqual(finalizedWinners([{ playerId: "b", points: 5 }, { playerId: "a", points: 5 }, { playerId: "c", points: 4 }]), ["a", "b"]); const ytd = yearToDatePoints([{ playerId: "a", points: 3, submittedAt: "2026-02-01T00:00:00Z", finalized: true }, { playerId: "a", points: 7, submittedAt: "2026-03-01T00:00:00Z", finalized: false }], 2026, "UTC"); assert.equal(ytd.get("a"), 3) })
test("normal archived player's active leaderboard score is removed at finalized cleanup", () => { const active = activeLeaderboardAfterArchivedCleanup([{ playerId: "normal-archived", score: 31, archived: true }, { playerId: "active", score: 33 }]); assert.deepEqual(active.map((row) => row.playerId), ["active"]) })
test("archived Memorial score remains on the active All-Time leaderboard", () => { const active = activeLeaderboardAfterArchivedCleanup([{ playerId: "memorial", score: 32, archived: true, memorial: true }]); assert.deepEqual(active, [{ playerId: "memorial", score: 32, archived: true, memorial: true }]) })
test("Memorial score survives Climbers finalization archived cleanup", () => { const before = [{ playerId: "memorial", score: 32, archived: true, memorial: true }, { playerId: "normal-archived", score: 31, archived: true }]; const after = activeLeaderboardAfterArchivedCleanup(before); assert.equal(after.find((row) => row.playerId === "memorial")?.score, 32); assert.equal(after.some((row) => row.playerId === "normal-archived"), false) })
test("Memorial player cannot submit a new current score", () => { const result = evaluate({ playerId: "memorial", playerStatus: "memorial" }); assert.equal(result.eligible, false); assert.match(result.rejectionReasons.join(" "), /Memorial players cannot submit/) })
test("current player earns Climbers by strictly passing a Memorial standing score", () => { const result = evaluate({ score: 31 }, [{ playerId: "krys", score: 35 }, { playerId: "memorial", score: 32, archived: true, memorial: true }]); assert.deepEqual(result.passedPlayerIds, ["memorial"]); assert.equal(result.climbersPoints, 1) })
test("Memorial historical Records remain attached to the same canonical UUID", () => { const result = evaluate({ id: "memorial-history", playerId: "memorial-canonical-uuid", playerStatus: "memorial", source: "historical_import", score: 29, appliedAt: "2026-08-08T00:00:00Z" }, [{ playerId: "memorial-canonical-uuid", score: 33, archived: true, memorial: true }]); assert.equal(result.eligible, true); assert.equal(result.playerId, "memorial-canonical-uuid"); assert.equal(result.pbResult, "better"); assert.equal(result.climbersPoints, 0) })
