import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const read = (path: string) => readFileSync(path, "utf8")

test("normal All-Time admin surfaces keep entry, history, and Climbers separate", () => {
  const hub = read("app/admin/records/page.tsx")
  assert.match(hub, /\/admin\/records\/entry/)
  assert.match(hub, /\/admin\/records\/history/)
  assert.match(hub, /\/admin\/records\/backfill/)
  assert.match(hub, /\/admin\/records\/climbers/)
  assert.match(read("app/admin/records/entry/page.tsx"), /record_all_time_normal_entry/)
  assert.match(read("app/admin/records/history/page.tsx"), /correct_all_time_record_entry/)
  assert.match(read("app/admin/records/history/page.tsx"), /void_all_time_record_entry/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /preview_all_time_late_backfill_entry/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /record_all_time_late_backfill_entry/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /preview_all_time_late_backfill_batch/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /record_all_time_late_backfill_batch/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /MULTI-PLAYER SCORECARD/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /ADD PLAYER/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /CompactScorecardGrid/)
  assert.match(read("components/admin/records/CompactScorecardGrid.tsx"), /data-hole-index/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /same_card_snapshot/)
  assert.match(read("app/admin/records/backfill/page.tsx"), /confirmation_token/)
  assert.match(read("app/admin/records/climbers/page.tsx"), /finalize_climbers_season/)
})

test("late/backdated entry keeps authoritative chronology separate and never creates a season", () => {
  const page = read("app/admin/records/backfill/page.tsx")
  assert.match(page, /Aug 15–Aug 28, 2026/)
  assert.match(page, /Exact original timestamp/)
  assert.match(page, /Date known \+ source-backed order/)
  assert.match(page, /No Climbers season is created by this page/)
  assert.match(page, /reviewed the canonical player, authoritative chronology/)
  assert.match(page, /request\.fingerprint !== previewFingerprint/)
  assert.match(read("app/admin/records/history/page.tsx"), /correct_all_time_late_backfill_entry/)
  assert.match(read("app/admin/records/history/page.tsx"), /correct_all_time_late_backfill_batch_entry/)
  assert.match(read("app/admin/records/history/page.tsx"), /card_batch_id/)
  assert.match(read("app/admin/records/history/page.tsx"), /void_all_time_late_backfill_entry/)
})

test("batch backfill UI preserves raw cards and explicit chronology safeguards", () => {
  const page = read("app/admin/records/backfill/page.tsx")
  assert.match(page, /Exact original timestamp/)
  assert.match(page, /Date known \+ source-backed order/)
  assert.match(page, /raw card cannot be saved safely yet/)
  assert.match(page, /No exact time is inferred/)
  assert.match(page, /Drafts exist only in this browser session/)
  assert.match(page, /CONFIRM AND SAVE ENTIRE CARD/)
  assert.match(page, /A canonical Global Player can appear only once/)
})

test("normal entry preview protects lower-is-better records and describes Climbers", () => {
  const page = read("app/admin/records/entry/page.tsx")
  assert.match(page, /CURRENT ALL-TIME PB/)
  assert.match(page, /NEED TO BEAT/)
  assert.match(page, /BETTER — passes/)
  assert.match(page, /FIRST — establishes a PB/)
  assert.match(page, /EQUAL — tie does not change the PB/)
  assert.match(page, /WORSE —/)
  assert.match(page, /from\("climbers_seasons"\)/)
  assert.match(page, /no active season \(0 points\)/)
  assert.match(page, /entryKeyRef/)
  assert.doesNotMatch(page, /preview_all_time_late_backfill/)
  assert.doesNotMatch(page, /HISTORICAL PB PENDING DATE\/ORDER/)
})

test("final intake is one-player, authoritative-par, and session-based", () => {
  const page = read("app/admin/records/entry/page.tsx")
  assert.match(page, /data-testid="normal-one-player-scorecard"/)
  assert.match(page, /<th scope="row">PAR<\/th>/)
  assert.match(page, /<th scope="row">SCORE<\/th>/)
  assert.match(page, /data-normal-hole-index/)
  assert.match(page, /focusAfterHole/)
  assert.match(page, /nextHoleAfterCompleteInput/)
  assert.match(page, /onWheel=/)
  assert.match(page, /ADD AGAIN/)
  assert.match(page, /ADD &amp; FINISH/)
  assert.match(page, /SESSION ENTRIES/)
  assert.match(page, /CURRENT PERIOD — DEFAULT/)
  assert.match(page, /PREVIOUS PERIOD/)
  assert.doesNotMatch(page, /Chronology evidence|datetime-local|Authoritative submitted date\/time|HISTORICAL PB PENDING DATE\/ORDER/)
  assert.match(page, /Previous Period saves are handled in the protected Late \/ Backfill tools/)
  assert.doesNotMatch(page, /ADD PLAYER|PREVIEW ENTIRE CARD|FRONT 9|BACK 9|P1|P2|P3/)
})

test("public records only expose detailed card statistics when holes and pars exist", () => {
  const route = read("app/api/records/public/route.ts")
  assert.match(route, /best_observation_id/)
  assert.match(route, /detailedCardStats/)
  assert.match(read("lib/all-time/public-records.ts"), /holeStrokes.length !== 18/)
})
