import type { FeatureRoute } from "@/lib/featureVisibility/core"

// Order matters: more specific routes precede their parent route.
export const FEATURE_ROUTES: readonly FeatureRoute[] = [
  { key: "amateur_pro", path: "/amateur-pro-standings", visibility: "private" },
  { key: "amateur_pro", path: "/amateur-pro", visibility: "private" },
  { key: "solo", path: "/solo", visibility: "private" },
  { key: "skins", path: "/skins-standings", visibility: "private" },
  { key: "skins", path: "/skins", visibility: "private" },
  { key: "records", path: "/records", visibility: "private" },
  { key: "tournaments", path: "/tournaments", visibility: "private" },
  { key: "invitationals", path: "/invitationals", visibility: "private" },
  { key: "kwt", path: "/kwt", visibility: "private" },
  { key: "monthlies", path: "/monthlies", visibility: "live" },
  { key: "register", path: "/register/success", visibility: "live" },
  { key: "player_dashboard", path: "/player-dashboard", visibility: "live" },
  { key: "players", path: "/players", visibility: "live" },
  { key: "league_play", path: "/league-play", visibility: "live" },
  { key: "match_standings", path: "/match-standings", visibility: "live" },
  { key: "match_play", path: "/match-play", visibility: "live" },
  { key: "doubles_standings", path: "/doubles-standings", visibility: "live" },
  { key: "pyp_standings", path: "/pyp-standings", visibility: "live" },
  { key: "join", path: "/join", visibility: "live" },
  { key: "register", path: "/register", visibility: "live" },
  { key: "player_dashboard", path: "/dashboard", visibility: "live" },
  { key: "stroke", path: "/stroke", visibility: "live" },
  { key: "standings", path: "/standings", visibility: "live" },
  { key: "schedule", path: "/schedule", visibility: "live" },
  { key: "matches", path: "/matches", visibility: "live" },
  { key: "doubles", path: "/doubles", visibility: "live" },
  { key: "pyp", path: "/pyp", visibility: "live" },
  { key: "champions", path: "/champions", visibility: "live" },
  { key: "leaderboards", path: "/leaderboards", visibility: "live" },
  { key: "main_hub", path: "/", visibility: "live" },
] as const
