"use client"
/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-unused-vars */
import {useCallback,useEffect,useMemo,useState} from "react"
import {useRouter} from "next/navigation"
import {supabase} from "@/lib/supabase"
import {SOLO_DIVISIONS,SOLO_DIVISION_PRESENTATION,type SoloDivision} from "@/lib/solo"
import styles from "./standings.module.css"
type Week={id:string;week_number:number;status:"open"|"closed";course_code:string|null}
type Entry={player_id:string;player_screen_name:string;division:SoloDivision;display_order:number}
type Frozen={week_id:string;player_id:string;easy_stroke_score:number|null;hard_stroke_score:number|null}
type Cell={easy:number|null;hard:number|null}
type StandingRow={player:Entry;cells:Cell[];total:number|null;rank:number|null}

export default function SoloStandingsPage(){
 const router=useRouter(),[seasonId,setSeasonId]=useState(""),[seasonNumber,setSeasonNumber]=useState<number|null>(null),[weeks,setWeeks]=useState<Week[]>([]),[entries,setEntries]=useState<Entry[]>([]),[frozen,setFrozen]=useState<Frozen[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{const id=new URLSearchParams(location.search).get("seasonId")||"";setSeasonId(id);if(!id){setMessage("A seasonId is required.");setLoading(false);return}const [{data:s,error:se},{data:w,error:we},{data:r,error:re},{data:snaps,error:sne}]=await Promise.all([supabase.from("seasons").select("season_number,league_type").eq("id",id).maybeSingle(),supabase.from("solo_weeks").select("id,week_number,status,course_code").eq("season_id",id).order("week_number"),supabase.from("solo_roster_versions").select("id").eq("season_id",id).eq("status","approved").maybeSingle(),supabase.from("solo_week_snapshots").select("id").eq("season_id",id).eq("is_current",true)]);if(se||we||re||sne||!s||s.league_type!=="solo"||!r){setMessage(se?.message||we?.message||re?.message||sne?.message||"Exact Solo season not found.");setLoading(false);return}const snapshotIds=(snaps||[]).map(x=>x.id),[{data:e,error:ee},{data:f,error:fe}]=await Promise.all([supabase.from("solo_roster_entries").select("player_id,player_screen_name,division,display_order").eq("roster_version_id",r.id).order("display_order"),snapshotIds.length?supabase.from("solo_week_snapshot_entries").select("week_id,player_id,easy_stroke_score,hard_stroke_score").in("snapshot_id",snapshotIds):Promise.resolve({data:[],error:null})]);if(ee||fe){setMessage(ee?.message||fe?.message||"");setLoading(false);return}setSeasonNumber(s.season_number);setWeeks(w as Week[]);setEntries(e as Entry[]);setFrozen(f as Frozen[]);setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const boards=useMemo(()=>SOLO_DIVISIONS.map(division=>{const ordered=entries.filter(e=>e.division===division).map(player=>{const cells=weeks.map(week=>{if(week.status!=="closed")return{easy:null,hard:null};const row=frozen.find(x=>x.week_id===week.id&&x.player_id===player.player_id);return{easy:row?.easy_stroke_score??null,hard:row?.hard_stroke_score??null}}),scores=cells.flatMap(c=>[c.easy,c.hard]).filter((x):x is number=>x!==null);return{player,cells,total:scores.length?scores.reduce((sum,score)=>sum+score,0):null}}).sort((a,b)=>a.total===null?1:b.total===null?-1:a.total-b.total||a.player.display_order-b.player.display_order);const rows:StandingRow[]=ordered.map((row,index)=>({...row,rank:row.total===null?null:ordered.findIndex(candidate=>candidate.total===row.total)+1}));return{division,rows}}),[entries,weeks,frozen])
 return <main className={styles.page}><nav><button onClick={()=>router.push(`/admin/solo?seasonId=${seasonId}`)}>Back to Solo Hub</button><button onClick={()=>router.push(`/admin/solo/results?seasonId=${seasonId}`)}>Enter Scores</button><button onClick={()=>router.push(`/admin/solo/share?seasonId=${seasonId}`)}>Share Boards</button></nav><h1>Krys Leagues Solo — Season {seasonNumber??"—"}</h1>{loading?<p>Loading…</p>:boards.map(({division,rows})=><section key={division} style={{"--division":SOLO_DIVISION_PRESENTATION[division].color} as React.CSSProperties}><h2>{SOLO_DIVISION_PRESENTATION[division].symbol} {division} · Season {seasonNumber??"—"}</h2><div className={styles.scroll}><table><colgroup><col className={styles.rank}/><col className={styles.total}/><col className={styles.player}/>{weeks.flatMap(w=>[<col className={styles.score} key={`${w.id}e`}/>,<col className={styles.score} key={`${w.id}h`}/>])}</colgroup><thead><tr><th rowSpan={2}>RANK</th><th rowSpan={2}>ST</th><th rowSpan={2}>PLAYER</th>{weeks.map(w=><th colSpan={2} key={w.id}>WEEK {w.week_number}</th>)}</tr><tr>{weeks.flatMap(w=>[<th key={`${w.id}e`}>{w.course_code?`${w.course_code}E`:"E"}</th>,<th key={`${w.id}h`}>{w.course_code?`${w.course_code}H`:"H"}</th>])}</tr></thead><tbody>{rows.map(r=><tr key={r.player.player_id}><td>{r.rank??"—"}</td><td><b>{r.total??"—"}</b></td><td><b>{r.player.player_screen_name}</b></td>{r.cells.flatMap((c,i)=>[<td key={`${i}e`}>{c.easy??"—"}</td>,<td key={`${i}h`}>{c.hard??"—"}</td>])}</tr>)}</tbody></table></div></section>)}{message&&<p>{message}</p>}</main>
}
