"use client"
/* eslint-disable react-hooks/set-state-in-effect */
import {useCallback,useEffect,useMemo,useState} from "react"
import {useRouter} from "next/navigation"
import {supabase} from "@/lib/supabase"
import {SOLO_DIVISIONS,SOLO_DIVISION_PRESENTATION,type SoloDivision} from "@/lib/solo"
type Week={id:string;week_number:number;status:"open"|"closed"};type Entry={player_id:string;player_screen_name:string;division:SoloDivision;display_order:number};type Frozen={week_id:string;player_id:string;easy_stroke_score:number|null;hard_stroke_score:number|null};type Season={season_number:number;league_type:string|null}
export default function SoloStandingsPage(){
 const router=useRouter();const [seasonId,setSeasonId]=useState("");const [season,setSeason]=useState<Season|null>(null);const [weeks,setWeeks]=useState<Week[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [frozen,setFrozen]=useState<Frozen[]>([]);const [division,setDivision]=useState<SoloDivision>("Master");const [message,setMessage]=useState("");const [loading,setLoading]=useState(true)
 const load=useCallback(async()=>{const id=new URLSearchParams(window.location.search).get("seasonId")||"";setSeasonId(id);if(!id){setMessage("A seasonId is required. No fallback season was loaded.");setLoading(false);return}const [{data:s,error:se},{data:w,error:we},{data:r,error:re}]=await Promise.all([supabase.from("seasons").select("season_number,league_type").eq("id",id).maybeSingle(),supabase.from("solo_weeks").select("id,week_number,status").eq("season_id",id).order("week_number"),supabase.from("solo_roster_versions").select("id").eq("season_id",id).eq("status","approved").maybeSingle()]);if(se||we||re||!s||s.league_type!=="solo"||!r){setMessage(se?.message||we?.message||re?.message||"Exact managed Solo season was not found.");setLoading(false);return}const {data:snaps,error:snapError}=await supabase.from("solo_week_snapshots").select("id").eq("season_id",id).eq("is_current",true);const ids=(snaps||[]).map(x=>x.id);const [{data:e,error:ee},{data:f,error:fe}]=await Promise.all([supabase.from("solo_roster_entries").select("player_id,player_screen_name,division,display_order").eq("roster_version_id",r.id).order("display_order"),ids.length?supabase.from("solo_week_snapshot_entries").select("week_id,player_id,easy_stroke_score,hard_stroke_score").in("snapshot_id",ids):Promise.resolve({data:[] as Frozen[],error:null})]);if(snapError||ee||fe){setMessage(snapError?.message||ee?.message||fe?.message||"");setLoading(false);return}setSeason(s as Season);setWeeks((w||[]) as Week[]);setEntries((e||[]) as Entry[]);setFrozen((f||[]) as Frozen[]);setLoading(false)},[])
 useEffect(()=>{void load()},[load]);const closedIds=useMemo(()=>new Set(weeks.filter(w=>w.status==="closed").map(w=>w.id)),[weeks]);const rows=useMemo(()=>entries.filter(e=>e.division===division).map(player=>{const scores=frozen.filter(f=>f.player_id===player.player_id&&closedIds.has(f.week_id)),easyScores=scores.filter(s=>s.easy_stroke_score!==null),hardScores=scores.filter(s=>s.hard_stroke_score!==null),easy=easyScores.reduce((sum,s)=>sum+s.easy_stroke_score!,0),hard=hardScores.reduce((sum,s)=>sum+s.hard_stroke_score!,0),missingEasy=closedIds.size-easyScores.length,missingHard=closedIds.size-hardScores.length;return{player,easy,hard,combined:easy+hard,missingEasy,missingHard,complete:closedIds.size>0&&missingEasy===0&&missingHard===0}}).sort((a,b)=>Number(b.complete)-Number(a.complete)||(a.complete?a.combined-b.combined:a.player.display_order-b.player.display_order)).map((row,index,array)=>({...row,rank:row.complete?array.findIndex(x=>x.complete&&x.combined===row.combined)+1:null})),[entries,division,frozen,closedIds])
 return <main style={page}><div style={container}><nav style={nav}><button style={button} onClick={()=>router.push(`/admin/solo?seasonId=${encodeURIComponent(seasonId)}`)}>← Solo Hub</button><button style={button} onClick={()=>router.push(`/admin/solo/results?seasonId=${encodeURIComponent(seasonId)}`)}>Results</button></nav><h1>Solo Standings</h1><p style={muted}>{season?`Season ${season.season_number} · official closed-week scores only`:"Load exact Solo season."}</p><div style={tabs}>{weeks.map(w=><span key={w.id} style={pill}>Week {w.week_number}: {w.status.toUpperCase()}</span>)}</div><div style={tabs}>{SOLO_DIVISIONS.map(d=><button key={d} style={d===division?active:button} onClick={()=>setDivision(d)}>{SOLO_DIVISION_PRESENTATION[d].symbol} {d}</button>)}</div>{loading?<p>Loading…</p>:<section style={panel}><h2>{SOLO_DIVISION_PRESENTATION[division].symbol} {division}</h2><div style={table}><strong>Rank</strong><strong>Player</strong><strong>Easy Total</strong><strong>Hard Total</strong><strong>Combined</strong><strong>Status</strong>{rows.map(r=><div key={r.player.player_id} style={{display:"contents"}}><span>{r.rank??"—"}</span><strong>{r.player.player_screen_name}</strong><span>{closedIds.size?r.easy:"—"}</span><span>{closedIds.size?r.hard:"—"}</span><strong>{closedIds.size?r.combined:"—"}</strong><span>{closedIds.size===0?"No closed weeks":r.complete?"Complete for closed weeks":`Missing ${r.missingEasy} Easy / ${r.missingHard} Hard`}</span></div>)}</div><p style={muted}>Missing scores are never converted to zero. Partial totals remain visible but incomplete players receive no official rank. Exact combined-total ties remain tied; no unconfirmed season HN1 formula is applied.</p></section>}{message&&<p style={notice}>{message}</p>}</div></main>
}
const page:React.CSSProperties={minHeight:"100vh",padding:24,background:"black",color:"white"};const container:React.CSSProperties={maxWidth:1100,margin:"0 auto"};const nav:React.CSSProperties={display:"flex",gap:10};const muted:React.CSSProperties={color:"#bbb"};const tabs:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",margin:"18px 0"};const button:React.CSSProperties={padding:"9px 12px",border:"1px solid #555",borderRadius:8,background:"#171717",color:"white"};const active:React.CSSProperties={...button,borderColor:"#67e8f9",color:"#67e8f9"};const pill:React.CSSProperties={...button,display:"inline-block"};const panel:React.CSSProperties={padding:18,border:"1px solid #333",borderRadius:12,background:"#0d0d0d"};const table:React.CSSProperties={display:"grid",gridTemplateColumns:"60px minmax(140px,1fr) repeat(3,minmax(90px,auto)) minmax(180px,1fr)",gap:12,alignItems:"center"};const notice:React.CSSProperties={padding:12,border:"1px solid #555",borderRadius:8,background:"#171717"}
