"use client"

import Link from "next/link"
import Papa from "papaparse"
import { useMemo, useState } from "react"
import { loadGlobalPlayerDirectory } from "@/lib/identity/globalPlayerDirectory"
import { previewCompetitionRows, type CompetitionImportKind, type CompetitionPreview } from "@/lib/importer/adapters/competitionPreview"
import { MONTHLY_PUBLIC_URL } from "@/lib/externalCompetitionSites"
import type { MonthlyPublicDiscovery } from "@/lib/importer/monthlyPublicSource"

type Props = { initialKind: CompetitionImportKind; title: string; description: string; allowKindSelection?: boolean; monthlyDiscovery?: MonthlyPublicDiscovery | null; monthlyDiscoveryError?: string }
const kinds: Array<{ value: CompetitionImportKind; label: string }> = [
  { value: "tournament", label: "Tournament" }, { value: "invitational", label: "Invitational" }, { value: "monthly", label: "Monthly" },
]
const card = "rounded-xl border border-zinc-800 bg-zinc-900 p-5"

export default function CompetitionImporter({ initialKind, title, description, allowKindSelection = false, monthlyDiscovery = null, monthlyDiscoveryError = "" }: Props) {
  const [kind, setKind] = useState<CompetitionImportKind>(initialKind)
  const [fileName, setFileName] = useState("")
  const [preview, setPreview] = useState<CompetitionPreview | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [problemSearch, setProblemSearch] = useState("")
  const [confirmHistoricalLock, setConfirmHistoricalLock] = useState(false)
  const [retrievedAt, setRetrievedAt] = useState<string | null>(null)
  const [sourceSaysCompleted, setSourceSaysCompleted] = useState(false)
  const problemRows = useMemo(() => {
    const query = problemSearch.trim().toLocaleLowerCase()
    return (preview?.rows ?? []).filter((row) => row.issues.length > 0).filter((row) => !query || row.historicalPlayerName.toLocaleLowerCase().includes(query) || row.issues.some((issue) => issue.toLocaleLowerCase().includes(query)))
  }, [preview, problemSearch])
  const divisions = useMemo(() => [...new Set((preview?.rows ?? []).map(row => row.division).filter(Boolean))], [preview])
  const courses = useMemo(() => [...new Set((preview?.rows ?? []).flatMap(row => row.rounds.map(round => round.courseCode)).filter(Boolean))], [preview])
  const periods = useMemo(() => [...new Set((preview?.rows ?? []).map(row => row.season).filter(Boolean))], [preview])

  async function analyze(file: File) {
    setLoading(true); setError(""); setPreview(null); setFileName(file.name)
    try {
      const parsed = Papa.parse<Record<string, string>>(await file.text(), { header: true, skipEmptyLines: "greedy", transformHeader: (header) => header.trim() })
      if (parsed.errors.length > 0) throw new Error(parsed.errors[0].message)
      if (parsed.data.length === 0) throw new Error("The CSV contains no data rows.")
      setRetrievedAt(new Date().toISOString())
      setSourceSaysCompleted(parsed.data.some(row => Object.values(row).some(value => /^completed$/i.test(String(value).trim()))))
      const players = await loadGlobalPlayerDirectory()
      setPreview(previewCompetitionRows(parsed.data, { kind, filename: file.name, players: players.map((player) => ({ id: player.id, screenName: player.screenName, verifiedAliases: player.verifiedAliases, status: player.status, active: player.active, memorial: player.status === "memorial" })) }))
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The file could not be previewed.") }
    finally { setLoading(false) }
  }

  return <main className="min-h-screen bg-zinc-950 px-6 py-10 text-white"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-300">Local V2 · Preview only</p><h1 className="mt-2 text-4xl font-bold">{title}</h1><p className="mt-3 max-w-3xl text-zinc-400">{description}</p></div><Link href="/admin/import" className="rounded-lg border border-zinc-700 px-4 py-2 font-semibold">← Import Center</Link></div>
    <section className={`${card} mt-8 border-amber-800 bg-amber-950/30`}><strong className="text-amber-200">Safe preview checkpoint</strong><p className="mt-2 text-amber-100/80">This screen reads Global Players and verified aliases for matching. It does not create import batches, write history, remember aliases, or mutate Production data.</p></section>
    {allowKindSelection && <section className={`${card} mt-6`}><label className="font-semibold" htmlFor="competition-kind">Source event type</label><p className="mt-1 text-sm text-zinc-400">Choose only what the source identifies. Do not infer an event type.</p><select id="competition-kind" value={kind} onChange={(event) => { setKind(event.target.value as CompetitionImportKind); setPreview(null) }} className="mt-3 rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3">{kinds.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></section>}
    {kind === "monthly" && <section className={`${card} mt-6 border-indigo-800`}><h2 className="text-xl font-bold">Public Monthly history source</h2><p className="mt-2 text-zinc-300"><a className="text-indigo-300 underline" href={MONTHLY_PUBLIC_URL} target="_blank" rel="noreferrer">Open the stable public Monthly site</a>. Capture published division standings and every individual-course table. Ignore the cross-division Overall Leaders table; never reconstruct division standings from course rows.</p><p className="mt-2 text-zinc-300">COMPLETED is optional source evidence, never a required field. Current/open standings may be fetched and previewed but cannot be treated as final without the decision below.</p><label className="mt-4 flex items-start gap-3 rounded-lg border border-amber-800 bg-amber-950/30 p-4"><input type="checkbox" checked={confirmHistoricalLock} onChange={event => setConfirmHistoricalLock(event.target.checked)} /><span><strong>Confirm this month is final / locked</strong><br/><span className="text-sm text-amber-100/80">Required before a future Apply unless reliable source-backed final evidence is approved.</span></span></label><p className="mt-3 font-semibold text-amber-200">Historical Monthly rows earn 0 Climbers.</p></section>}
    {kind === "monthly" && <section className={`${card} mt-4`}><h3 className="text-lg font-bold">Read-only source discovery</h3>{monthlyDiscoveryError ? <p className="mt-2 text-red-300">{monthlyDiscoveryError}</p> : monthlyDiscovery ? <dl className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><div><dt className="text-zinc-500">Month / year</dt><dd>{monthlyDiscovery.monthYear || "Not supplied"}</dd></div><div><dt className="text-zinc-500">Source says COMPLETED</dt><dd>{monthlyDiscovery.sourceSaysCompleted ? "Yes (optional evidence)" : "Not present"}</dd></div><div><dt className="text-zinc-500">Source says In Progress</dt><dd>{monthlyDiscovery.sourceSaysInProgress ? "Yes" : "Not present"}</dd></div><div><dt className="text-zinc-500">Division standings</dt><dd>{monthlyDiscovery.divisionStandingsFound}</dd></div><div><dt className="text-zinc-500">Course tables</dt><dd>{monthlyDiscovery.courseTablesFound}</dd></div><div><dt className="text-zinc-500">Retrieved</dt><dd>{monthlyDiscovery.retrievedAt}</dd></div><div className="sm:col-span-2"><dt className="text-zinc-500">Exact source URL</dt><dd className="break-all">{monthlyDiscovery.sourceUrl}</dd></div></dl> : <p>No source snapshot loaded.</p>}</section>}
    <section className={`${card} mt-6`}><label className="flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-zinc-700 p-10 text-center hover:border-indigo-400"><span className="text-3xl">CSV</span><strong className="mt-3 text-xl">Choose a source file</strong><span className="mt-2 text-zinc-400">Upload → parse → canonical identity preview. Nothing is applied.</span><input className="hidden" type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) void analyze(file); event.target.value = "" }} /></label>{loading && <p className="mt-4 text-indigo-200">Parsing {fileName} and resolving players…</p>}{error && <p className="mt-4 rounded-lg border border-red-800 bg-red-950 p-4 text-red-200">{error}</p>}</section>
    {preview && <>
      {kind === "kwt" && <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Seasons / weeks", [...new Set(preview.rows.map(row => `${row.season ?? "?"}/${row.week ?? "?"}`))].length], ["Players", new Set(preview.rows.map(row => row.canonicalPlayerId ?? row.historicalPlayerName)).size], ["Easy scores", preview.summary.easyScores], ["Hard scores", preview.summary.hardScores], ["Missing Easy", preview.summary.missingEasyScores], ["Missing Hard", preview.summary.missingHardScores], ["Divisions found", preview.summary.divisionsFound], ["Divisions missing", preview.summary.divisionsMissing], ["Placements found", preview.summary.placementsFound], ["Placements missing", preview.summary.placementsMissing], ["Safe, optional facts missing", preview.summary.safeWithOptionalFieldsMissing], ["Conflicting observations", preview.summary.conflicts]].map(([label, value]) => <div className={card} key={label}><p className="text-sm uppercase tracking-wide text-zinc-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</section>}
      <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Rows / results", preview.summary.totalRows], ["Month / year", periods.join(", ") || "Not supplied"], ["Division standings found", divisions.length], ["Course tables found", courses.length], ["Source says COMPLETED", kind === "monthly" ? (sourceSaysCompleted ? "Yes" : "Not present") : "N/A"], ["Source retrieved at", retrievedAt || "Not recorded"], ["Resolved players", preview.summary.resolvedPlayers], ["Archived resolved", preview.summary.archivedPlayersResolved], ["Memorial resolved", preview.summary.memorialPlayersResolved], ["Unresolved players", preview.summary.unresolvedPlayers], ["Ambiguous players", preview.summary.ambiguousPlayers], ["Missing source facts", preview.summary.missingSourceFacts], ["Duplicates", preview.summary.duplicates], ["Safe rows", preview.summary.safeToApply], ["Blocked rows", preview.summary.blocked], ["Source URL", kind === "monthly" ? MONTHLY_PUBLIC_URL : fileName]].map(([label, value]) => <div className={card} key={label}><p className="text-sm uppercase tracking-wide text-zinc-500">{label}</p><p className="mt-2 break-all text-2xl font-bold">{value}</p></div>)}</section>
      {preview.summary.blocked > 0 && <section className={`${card} mt-6 border-red-900`}><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold text-red-200">Problems requiring review</h2><p className="mt-1 text-zinc-400">Ambiguous players are never guessed.</p></div><input value={problemSearch} onChange={(event) => setProblemSearch(event.target.value)} placeholder="Search player or problem" className="rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-2" /></div><div className="mt-4 space-y-3">{problemRows.map((row) => <article key={row.sourceRow} className="rounded-lg border border-zinc-800 bg-zinc-950 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>Row {row.sourceRow}: {row.historicalPlayerName || "Missing player"}</strong><span className="text-red-300">{row.identityStatus}</span></div><ul className="mt-2 list-disc pl-5 text-sm text-zinc-300">{row.issues.map((issue) => <li key={issue}>{issue}</li>)}</ul>{row.identityCandidates.length > 0 && <p className="mt-2 text-sm text-amber-200">Candidates: {row.identityCandidates.map((candidate) => candidate.screenName).join(", ")}</p>}</article>)}</div></section>}
      <section className={`${card} mt-6 overflow-x-auto`}><h2 className="text-2xl font-bold">Parsed source rows</h2><table className="mt-4 min-w-full text-left text-sm"><thead className="border-b border-zinc-700 text-zinc-400"><tr>{["Row", "Player snapshot", "Canonical player", "Event / season", "Division", "Easy", "Hard", "Published Pos / Placement", "Status"].map((heading) => <th className="px-3 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody>{preview.rows.map((row) => <tr className="border-b border-zinc-800" key={row.sourceRow}><td className="px-3 py-3">{row.sourceRow}</td><td className="px-3 py-3">{row.historicalPlayerName || "—"}</td><td className="px-3 py-3">{row.canonicalPlayerName || "—"}</td><td className="px-3 py-3">{row.kind === "kwt" ? `Season ${row.season ?? "—"}, Week ${row.week ?? "—"}` : row.eventName || "—"}</td><td className="px-3 py-3">{row.division || "—"}</td><td className="px-3 py-3">{row.rounds.find(round => round.difficulty === "easy")?.courseCode || "—"} {row.rounds.find(round => round.difficulty === "easy")?.score ?? "—"}</td><td className="px-3 py-3">{row.rounds.find(round => round.difficulty === "hard")?.courseCode || "—"} {row.rounds.find(round => round.difficulty === "hard")?.score ?? "—"}</td><td className="px-3 py-3">{row.publishedPosition || row.placement || "—"}</td><td className={`px-3 py-3 ${row.issues.length ? "text-red-300" : row.warnings.length ? "text-amber-300" : "text-green-300"}`}>{row.issues.length ? "Blocked" : row.warnings.length ? "Safe · optional fields missing" : "Safe"}{row.warnings.length > 0 && <span className="mt-1 block text-xs">{row.warnings.join(" ")}</span>}</td></tr>)}</tbody></table></section>
      <section className={`${card} mt-6 flex flex-wrap items-center justify-between gap-4`}><div><h2 className="text-xl font-bold">Dry run checkpoint</h2><p className="mt-1 text-zinc-400">File-level duplicate and identity review is available. {kind === "monthly" && !confirmHistoricalLock ? "Historical lock confirmation is still required. " : ""}Database duplicate checking and destination writes remain disconnected pending migration approval.</p></div><div className="flex gap-2"><button type="button" disabled className="cursor-not-allowed rounded-lg bg-zinc-700 px-6 py-3 font-bold text-zinc-400">Dry run unavailable</button><button type="button" disabled className="cursor-not-allowed rounded-lg bg-zinc-700 px-6 py-3 font-bold text-zinc-400">Apply disabled</button></div></section>
    </>}
  </div></main>
}
