"use client"

import Link from "next/link"
import Papa from "papaparse"
import { useState } from "react"
import { loadGlobalPlayerDirectory } from "@/lib/identity/globalPlayerDirectory"
import { previewKwtLibrary, type KwtLibraryPreview } from "@/lib/importer/adapters/kwtLibraryPreview"

const card = "rounded-xl border border-zinc-800 bg-zinc-900 p-5"
const statusClass = (status: string) => status === "READY" ? "text-green-300" : status === "NO SOURCE" ? "text-zinc-500" : "text-amber-300"

async function sha256(file: File) {
  const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer())
  return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join("")
}

export default function KwtLibraryImporter() {
  const [preview, setPreview] = useState<KwtLibraryPreview | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")

  async function analyze(files: File[]) {
    setLoading(true); setError(""); setPreview(null)
    try {
      const sources = await Promise.all(files.map(async file => {
        const parsed = Papa.parse<Record<string, string>>(await file.text(), { header: true, skipEmptyLines: "greedy", transformHeader: header => header.trim() })
        if (parsed.errors.length) throw new Error(`${file.name}: ${parsed.errors[0].message}`)
        return { filename: file.name, sourceHash: await sha256(file), rows: parsed.data }
      }))
      const directory = await loadGlobalPlayerDirectory()
      setPreview(previewKwtLibrary(sources, directory.map(player => ({ id: player.id, screenName: player.screenName, verifiedAliases: player.verifiedAliases, status: player.status, active: player.active, memorial: player.status === "memorial" }))))
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The KWT library could not be previewed.") }
    finally { setLoading(false) }
  }

  return <main className="min-h-screen bg-zinc-950 px-6 py-10 text-white"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-300">Local V2 · Preview only</p><h1 className="mt-2 text-4xl font-bold">KWT score-history library</h1><p className="mt-3 max-w-3xl text-zinc-400">Compare every CSV variant by Season + Week, resolve current canonical identities, and review authoritative Easy/Hard score coverage. No Apply path is connected.</p><Link href="/admin/kwt-import/discord-season-9" className="mt-4 inline-block rounded-lg bg-indigo-600 px-4 py-2 font-bold">Review Season 9 Discord evidence →</Link></div><Link href="/admin/import" className="rounded-lg border border-zinc-700 px-4 py-2 font-semibold">← Import Center</Link></div>
    <section className={`${card} mt-8 border-amber-800 bg-amber-950/30`}><strong className="text-amber-200">Historical baseline only · 0 Climbers</strong><p className="mt-2 text-amber-100/80">A future successful Apply may establish or improve All-Time PB terrain from its explicit appliedAt time forward. It never replays or erases earlier Climbers.</p></section>
    <section className={`${card} mt-6`}><label className="flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-zinc-700 p-10 text-center hover:border-indigo-400"><strong className="text-xl">Choose multiple KWT CSV files</strong><span className="mt-2 text-zinc-400">Files are hashed and parsed locally, then matched against the current canonical directory.</span><input className="hidden" multiple type="file" accept=".csv,text/csv" onChange={event => { const files = [...(event.target.files ?? [])]; if (files.length) void analyze(files); event.target.value = "" }} /></label>{loading && <p className="mt-4 text-indigo-200">Hashing, grouping, comparing, and resolving the library…</p>}{error && <p className="mt-4 text-red-300">{error}</p>}</section>
    {preview && <>
      <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[["Source periods", preview.periods.length], ["Ready", preview.summary.ready], ["Needs source choice", preview.summary.sourceChoice], ["Score-data problems", preview.summary.scoreProblems], ["Identity blocked", preview.summary.identityBlocked], ["Easy / Hard ready", `${preview.summary.easyReady} / ${preview.summary.hardReady}`]].map(([label, value]) => <div className={card} key={label}><p className="text-sm uppercase tracking-wide text-zinc-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</section>
      <section className={`${card} mt-6 overflow-x-auto`}><h2 className="text-2xl font-bold">Seasons 4–14 coverage</h2><p className="mt-2 text-zinc-400">Saved handicap inventory is a read-only snapshot. Identity status is rerun against the current directory on every preview. Download-time Rank Code and Pos are not historical rank evidence.</p><table className="mt-4 min-w-full text-left text-sm"><thead className="border-b border-zinc-700 text-zinc-400"><tr>{["Period","Saved handicap","CSV","Score-variant conflict","Identities","Missing score rows","Readiness"].map(value => <th className="px-3 py-2" key={value}>{value}</th>)}</tr></thead><tbody>{preview.coverage.map(period => <tr className="border-b border-zinc-800" key={`${period.season}-${period.week}`}><td className="px-3 py-2">S{period.season}-W{period.week}</td><td className="px-3 py-2">{period.savedHandicapRoundsPresent ? "Found" : "—"}</td><td className="px-3 py-2">{period.variants.length ? "Available" : "—"}</td><td className="px-3 py-2">{period.sourceVariantConflict ? "Review" : "—"}</td><td className="px-3 py-2">{period.variants.length ? (period.identitiesResolved ? "Resolved" : "Review") : "—"}</td><td className="px-3 py-2">{period.missingScoreFacts || "—"}</td><td className={`px-3 py-2 font-bold ${statusClass(period.status)}`}>{period.status}</td></tr>)}</tbody></table></section>
      <section className="mt-6 space-y-5"><h2 className="text-2xl font-bold">Source-variant review</h2><p className="text-zinc-400">Rank Code / division and Pos counts below describe download-time source-snapshot metadata only. They cannot award trophies, establish historical placement/division, or create career achievements without separate contemporaneous evidence.</p>{preview.periods.map(period => <article className={card} key={`${period.season}-${period.week}`}><div className="flex flex-wrap justify-between gap-3"><h3 className="text-xl font-bold">Season {period.season} · Week {period.week}</h3><strong className={statusClass(period.status)}>{period.status}</strong></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{period.variants.map(variant => <div className="rounded-lg border border-zinc-700 bg-zinc-950 p-4" key={variant.filename}><div className="flex flex-wrap justify-between gap-2"><strong className="break-all">{variant.filename}</strong>{variant.recommended && <span className="text-green-300">RECOMMENDED — MORE COMPLETE</span>}</div><p className="mt-2 break-all font-mono text-xs text-zinc-500">SHA-256 {variant.sourceHash}</p><p className="mt-3 text-sm text-zinc-300">{variant.rowCount} rows · Easy {variant.easyScoreCount} · Hard {variant.hardScoreCount} · Snapshot Rank Code {variant.divisionCount} · Snapshot Pos {variant.publishedPositionCount}</p>{variant.identicalCopies.length > 0 && <div className="mt-2 text-xs text-indigo-300">Identical score-observation copies:{variant.identicalCopies.map(copy => <p className="break-all" key={copy.sourceHash}>{copy.filename} · SHA-256 {copy.sourceHash}</p>)}</div>}{variant.duplicatePlayers.length > 0 && <p className="mt-2 text-amber-300">Duplicate player rows: {variant.duplicatePlayers.join(", ")}</p>}</div>)}</div>{period.subsetNotes.map(note => <p className="mt-3 text-green-200" key={note}>{note}</p>)}{period.conflicts.map(conflict => <div className="mt-4 rounded-lg border border-red-900 p-4" key={conflict.player}><strong className="text-red-200">Authoritative score conflict: {conflict.player}</strong><div className="mt-2 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr>{["File","Historical name","Easy","Hard","Snapshot Rank Code","Snapshot Pos","Total","Points"].map(value => <th className="px-2 py-2" key={value}>{value}</th>)}</tr></thead><tbody>{conflict.observations.map(item => <tr key={item.filename}><td className="px-2 py-2">{item.filename}</td><td className="px-2 py-2">{item.historicalName}</td><td className="px-2 py-2">{item.easyCourse ?? "—"} {item.easyScore ?? "—"}</td><td className="px-2 py-2">{item.hardCourse ?? "—"} {item.hardScore ?? "—"}</td><td className="px-2 py-2">{item.division ?? "—"}</td><td className="px-2 py-2">{item.publishedPosition ?? "—"}</td><td className="px-2 py-2">{item.totalScore ?? "—"}</td><td className="px-2 py-2">{item.points ?? "—"}</td></tr>)}</tbody></table></div></div>)}</article>)}</section>
      <section className={`${card} mt-6`}><h2 className="text-xl font-bold">Deterministic reconciliation contract</h2><p className="mt-2 text-zinc-300">EXACT MATCH preserves an idempotent observation. NEW MISSING PERIOD is a candidate insert. SOURCE ENRICHMENT keeps the score while adding stronger provenance, canonical identity, or source metadata. CONFLICT always requires admin review. Existing legitimate history is never blindly replaced.</p><p className="mt-3 text-zinc-400">Future accepted Easy/Hard observations may be handed to All-Time Records as historical evidence using canonical UUID, mapped course, source hash, semantic fingerprint, and explicit appliedAt. Apply remains disabled.</p><button disabled className="mt-4 cursor-not-allowed rounded-lg bg-zinc-700 px-6 py-3 font-bold text-zinc-400">Apply disabled</button></section>
    </>}
  </div></main>
}
