"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { supabase } from "@/lib/supabase"

type Season={season_number:number;due_date:string|null;end_date:string|null;league_type:string|null};type Roster={id:string;status:"draft"|"approved"|"locked";division_count:number};type Slot={division_number:number;player_id:string;player_screen_name:string};type Standing={player_id:string;division:string;points:number;wins:number;losses:number;ties:number;strokes:number;rank:number};type Card={id:string;status:"draft"|"approved";source_roster_version_id:string};type Entry={id:string;division_number:number;division_rank:number;player_id:string;player_screen_name:string;completed_game_count:number;wins:number;losses:number;ties:number;points:number;holes_won:number};type Detail={id:string;player_id:string;game_number:number;opponent_screen_name:string;player_role:string;course1_name:string;course1_difficulty:string|null;course1_player_hw:number;course1_opponent_hw:number;course2_name:string;course2_difficulty:string|null;course2_player_hw:number;course2_opponent_hw:number;player_total_hw:number;opponent_total_hw:number;outcome:string}
const themes:Record<number,string>={1:"#fb923c",2:"#4ade80",3:"#60a5fa",4:"#facc15",5:"#c084fc"}
export default function PypStandingsPage(){const router=useRouter();const [seasonId,setSeasonId]=useState("");const [season,setSeason]=useState<Season|null>(null);const [roster,setRoster]=useState<Roster|null>(null);const [slots,setSlots]=useState<Slot[]>([]);const [standings,setStandings]=useState<Standing[]>([]);const [card,setCard]=useState<Card|null>(null);const [entries,setEntries]=useState<Entry[]>([]);const [details,setDetails]=useState<Detail[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true)
const load=useCallback(async(id:string)=>{setLoading(true);const [{data:s,error:se},{data:r,error:re},{data:c,error:ce}]=await Promise.all([supabase.from("seasons").select("season_number,due_date,end_date,league_type").eq("id",id).maybeSingle(),supabase.from("pyp_roster_versions").select("id,status,division_count").eq("season_id",id).in("status",["draft","approved","locked"]).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("pyp_final_scorecards").select("id,status,source_roster_version_id").eq("season_id",id).in("status",["draft","approved"]).order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(se||re||ce||!s||!r||s.league_type!=="pyp"){setMessage(se?.message||re?.message||ce?.message||"Managed PYP season was not found.");setLoading(false);return}const rosterRow=r as Roster,cardRow=c as Card|null;if(rosterRow.status==="approved"&&cardRow?.status!=="approved"){for(let d=1;d<=rosterRow.division_count;d+=1){const {error}=await supabase.rpc("rebuild_pyp_standings",{p_season_id:id,p_division_number:d});if(error){setMessage(`Could not rebuild managed PYP standings: ${error.message}`);break}}}const [{data:sl},{data:st},{data:en},{data:de}]=await Promise.all([supabase.from("pyp_division_roster_slots").select("division_number,player_id,player_screen_name").eq("roster_version_id",rosterRow.id).not("player_id","is",null),supabase.from("season_standings").select("player_id,division,points,wins,losses,ties,strokes,rank").eq("league_type","pyp").eq("season_number",s.season_number),cardRow?supabase.from("pyp_final_scorecard_entries").select("id,division_number,division_rank,player_id,player_screen_name,completed_game_count,wins,losses,ties,points,holes_won").eq("scorecard_id",cardRow.id).order("division_number").order("division_rank"):Promise.resolve({data:[]}),cardRow?supabase.from("pyp_final_scorecard_fixture_details").select("id,player_id,game_number,opponent_screen_name,player_role,course1_name,course1_difficulty,course1_player_hw,course1_opponent_hw,course2_name,course2_difficulty,course2_player_hw,course2_opponent_hw,player_total_hw,opponent_total_hw,outcome").eq("scorecard_id",cardRow.id).order("game_number"):Promise.resolve({data:[]})]);setSeason(s as Season);setRoster(rosterRow);setCard(cardRow);setSlots((sl||[]) as Slot[]);setStandings((st||[]) as Standing[]);setEntries((en||[]) as Entry[]);setDetails((de||[]) as Detail[]);setLoading(false)},[])
useEffect(()=>{const id=new URLSearchParams(window.location.search).get("seasonId")||"";// eslint-disable-next-line react-hooks/set-state-in-effect
setSeasonId(id);if(id)void load(id);else{setMessage("A managed seasonId is required.");setLoading(false)}},[load])
async function generate(){setBusy(true);setMessage("");const {error}=await supabase.rpc("generate_pyp_final_scorecard",{p_season_id:seasonId});setBusy(false);if(error){setMessage(error.message);return}setMessage("PYP Final Scorecard draft generated.");await load(seasonId)}
async function approve(){if(!card||!window.confirm("Approve and freeze this PYP Final Scorecard?"))return;setBusy(true);setMessage("");const {error}=await supabase.rpc("approve_pyp_final_scorecard",{p_final_scorecard_id:card.id,p_approval_note:null});setBusy(false);if(error){setMessage(error.message);return}setMessage("Final Scorecard approved and frozen. The source roster is now locked.");await load(seasonId)}
const displayEntries=useMemo(()=>{if(entries.length)return entries;const names=new Map(slots.map(s=>[s.player_id,s]));return standings.flatMap(st=>{const slot=names.get(st.player_id);if(!slot)return[];return[{id:st.player_id,division_number:slot.division_number,division_rank:st.rank,player_id:st.player_id,player_screen_name:slot.player_screen_name,completed_game_count:st.wins+st.losses+st.ties,wins:st.wins,losses:st.losses,ties:st.ties,points:st.points,holes_won:st.strokes}]})},[entries,slots,standings]);const due=season?.due_date||season?.end_date
return (<main style={page}><div style={container}><nav style={nav}><button onClick={()=>router.push("/admin/pyp")}>← PYP Hub</button><button onClick={()=>router.push(`/admin/pyp/results?seasonId=${encodeURIComponent(seasonId)}`)} disabled={!seasonId}>Results Admin</button><button onClick={()=>router.push(`/admin/pyp/schedule?seasonId=${encodeURIComponent(seasonId)}`)} disabled={!seasonId}>Schedule &amp; Images</button></nav><h1>PYP Scorecard / Standings</h1><p style={muted}>{season?`Season ${season.season_number}`:"Managed PYP season"} · Roster {roster?.status||"—"} · Final Scorecard {card?.status||"not generated"}</p><div style={nav}>{roster?.status==="approved"&&card?.status!=="approved"&&<button disabled={busy} onClick={generate}>{busy?"Working...":card?"Regenerate Final Scorecard":"Generate Final Scorecard"}</button>}{card?.status==="draft"&&<button disabled={busy} onClick={approve}>Approve Final Scorecard</button>}</div>{loading?<p>Loading standings...</p>:Array.from({length:roster?.division_count||0},(_,i)=>i+1).map(division=><section key={division} style={{...cardStyle,borderColor:themes[division]||"#555"}}><header style={cardHeader}><h2 style={{color:themes[division]||"#ddd"}}>PYP D{division}</h2><strong>{due?`Due ${formatDate(due)}`:"Due date not set"}</strong></header><div style={tableWrap}><table style={table}><thead><tr><th>Rank</th><th>Player</th><th>Played</th><th>Points</th><th>Wins</th><th>Losses</th><th>Ties</th><th>Holes Won</th><th>Completed Games</th></tr></thead><tbody>{displayEntries.filter(e=>e.division_number===division).sort((a,b)=>a.division_rank-b.division_rank).map(entry=><tr key={entry.id}><td>{entry.division_rank}</td><td style={playerName}>{entry.player_screen_name}</td><td>{entry.completed_game_count}</td><td>{entry.points}</td><td>{entry.wins}</td><td>{entry.losses}</td><td>{entry.ties}</td><td>{entry.holes_won}</td><td>{entry.completed_game_count}</td></tr>)}</tbody></table></div>{entries.length>0&&<details style={detailBox}><summary>Fixture details</summary>{entries.filter(e=>e.division_number===division).map(entry=><div key={entry.id}><h3>{entry.player_screen_name}</h3>{details.filter(d=>d.player_id===entry.player_id).map(d=><p key={d.id}>Round {d.game_number} · {d.player_role.toUpperCase()} vs {d.opponent_screen_name} · {d.course1_name}{d.course1_difficulty?` (${d.course1_difficulty})`:""}: {entry.player_screen_name} {d.course1_player_hw} · {d.opponent_screen_name} {d.course1_opponent_hw} · {d.course2_name}{d.course2_difficulty?` (${d.course2_difficulty})`:""}: {entry.player_screen_name} {d.course2_player_hw} · {d.opponent_screen_name} {d.course2_opponent_hw} · Total {entry.player_screen_name} {d.player_total_hw} · {d.opponent_screen_name} {d.opponent_total_hw} · {d.outcome}</p>)}</div>)}</details>}</section>)}{message&&<p style={feedback}>{message}</p>}</div></main>)
}
function formatDate(value:string){return new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`))}
const page:React.CSSProperties={minHeight:"100vh",padding:24,background:"black",color:"white"};const container:React.CSSProperties={maxWidth:1200,margin:"0 auto"};const nav:React.CSSProperties={display:"flex",gap:10,flexWrap:"wrap",margin:"16px 0"};const muted:React.CSSProperties={color:"#aaa"};const cardStyle:React.CSSProperties={padding:20,margin:"18px 0",border:"2px solid",borderRadius:14,background:"#0d0d0d"};const cardHeader:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"};const tableWrap:React.CSSProperties={overflowX:"auto"};const table:React.CSSProperties={width:"100%",borderCollapse:"collapse",textAlign:"left"};const playerName:React.CSSProperties={fontSize:16,fontWeight:600,whiteSpace:"nowrap"};const detailBox:React.CSSProperties={marginTop:16,padding:12,border:"1px solid #333",borderRadius:8,color:"#ccc"};const feedback:React.CSSProperties={padding:12,border:"1px solid #444",borderRadius:8,background:"#171717"}
