"use client"
import Link from "next/link"
import {useEffect,useState} from "react"
import {supabase} from "@/lib/supabase"
type Season={id:string;season_number:number;is_active:boolean};type Roster={season_id:string;status:string}
export default function SoloAdminPage(){
 const [seasons,setSeasons]=useState<Season[]>([]),[managed,setManaged]=useState<Set<string>>(new Set()),[selectedId,setSelectedId]=useState(""),[message,setMessage]=useState("")
 useEffect(()=>{async function load(){const requested=new URLSearchParams(window.location.search).get("seasonId")||"",{data,error}=await supabase.from("seasons").select("id, season_number, is_active").eq("league_type","solo").is("division",null).order("season_number",{ascending:false});if(error)return setMessage(error.message);const found=(data||[]) as Season[],{data:rosters,error:rosterError}=found.length?await supabase.from("solo_roster_versions").select("season_id, status").in("season_id",found.map(s=>s.id)).in("status",["draft","approved","locked"]):{data:[],error:null};if(rosterError)return setMessage(rosterError.message);const ids=new Set(((rosters||[]) as Roster[]).map(r=>r.season_id));setSeasons(found);setManaged(ids);if(requested){if(!found.some(s=>s.id===requested))setMessage("The requested Solo season was not found. No fallback season was loaded.");else setSelectedId(requested)}else setSelectedId(found.find(s=>s.is_active&&ids.has(s.id))?.id||found.find(s=>ids.has(s.id))?.id||"")}void load()},[])
 const selected=seasons.find(s=>s.id===selectedId),ready=Boolean(selected&&managed.has(selected.id)),href=(route:string)=>`${route}?seasonId=${encodeURIComponent(selectedId)}`
 return <main style={page}><div style={container}><h1 style={title}>Solo Admin Hub</h1><p style={subtitle}>Managed Solo seasons, flexible division rosters, and four-week setup.</p><section style={panel}><label style={label}>Managed season<select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setMessage("");window.history.replaceState(null,"",e.target.value?`${location.pathname}?seasonId=${encodeURIComponent(e.target.value)}`:"/admin/solo")}} style={input}><option value="">Choose a Solo season</option>{seasons.map(s=><option key={s.id} value={s.id}>Season {s.season_number}{s.is_active?" · Active":""}{managed.has(s.id)?" · Managed":" · Setup missing"}</option>)}</select></label>{message&&<p style={notice}>{message}</p>}</section><div style={grid}><Link href={selectedId?href("/admin/solo/season"):"/admin/solo/season"} style={card}><strong>Season Setup</strong><span>Create a season or review the selected season.</span></Link>{ready?<><Link href={href("/admin/solo/setup")} style={card}><strong>Setup / Roster</strong><span>Assign canonical players to Solo divisions.</span></Link><Link href={href("/admin/solo/weeks")} style={card}><strong>Weeks / Courses</strong><span>Save courses and close or reopen weeks.</span></Link><Link href={href("/admin/solo/results")} style={primaryCard}><strong>Enter Scores</strong><span>Go directly to current Solo score entry.</span></Link><Link href={href("/admin/solo/standings")} style={card}><strong>Standings</strong><span>View live and frozen Solo totals.</span></Link><Link href={href("/admin/solo/share")} style={card}><strong>Share Boards</strong><span>Open screenshot-friendly Solo boards.</span></Link><Link href="/solo" style={card}><strong>Public Solo Page</strong><span>View the actual player-facing Solo page.</span></Link></>:<><Disabled title="Setup / Roster"/><Disabled title="Weeks / Courses"/><Disabled title="Enter Scores"/><Disabled title="Standings"/><Disabled title="Share Boards"/><Link href="/solo" style={card}><strong>Public Solo Page</strong><span>View the public Solo page.</span></Link></>}</div></div></main>
}
function Disabled({title}:{title:string}){return <div style={{...card,opacity:.55}}><strong>{title}</strong><span>Select a managed Solo season first.</span></div>}
const page:React.CSSProperties={minHeight:"100vh",padding:24,background:"black",color:"white"},container:React.CSSProperties={maxWidth:1100,margin:"0 auto"},title:React.CSSProperties={fontSize:34,marginBottom:8},subtitle:React.CSSProperties={color:"#bbb",marginBottom:24},panel:React.CSSProperties={padding:18,border:"1px solid #333",borderRadius:14,background:"#0d0d0d",marginBottom:20},label:React.CSSProperties={display:"flex",flexDirection:"column",gap:8,fontWeight:800},input:React.CSSProperties={padding:11,background:"#111",color:"white",border:"1px solid #444",borderRadius:8},notice:React.CSSProperties={color:"#fca5a5"},grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14},card:React.CSSProperties={display:"flex",flexDirection:"column",gap:8,padding:18,borderRadius:14,border:"1px solid #333",background:"#111",color:"white",textDecoration:"none"},primaryCard:React.CSSProperties={...card,borderColor:"#22c55e",background:"#12351f"}
